import { JourneyDef, JourneyDifficulty } from "./journey-types";

// ─── Journey Definitions ──────────────────────────────────────────────────────

const frontLever: JourneyDef = {
  id:             "front_lever",
  name:           "Front Lever Journey",
  subtitle:       "The Path to Horizontal Mastery",
  description:    "The front lever is the pinnacle of pulling strength. This journey takes you from basic hangs to horizontal mastery.",
  icon:           "🌊",
  category:       "pull",
  difficulty:     "elite",
  estimatedWeeks: 16,
  featured:       true,
  tags:           ["pull", "static", "strength", "rings", "bar"],
  stages: [
    {
      id:          "fl_stage_1",
      stageNumber: 1,
      name:        "Dead Hang Foundation",
      description: "Build the grip and shoulder strength needed for lever work.",
      icon:        "🧱",
      isMilestone: false,
      tips:        ["Build grip strength with daily hangs", "Use a pull-up bar or rings", "Focus on active shoulder engagement"],
      requirements: [
        { type: "record_seconds", target: "dead_hang", value: 10,  label: "10s Dead Hang",  description: "Set a Dead Hang record of at least 10 seconds" },
        { type: "workout_count",  target: "",           value: 5,   label: "5 Workouts",     description: "Log at least 5 workouts" },
      ],
      reward: { xp: 100, coins: 25, description: "Dead Hang Foundation complete" },
    },
    {
      id:          "fl_stage_2",
      stageNumber: 2,
      name:        "Pull-Up Power",
      description: "Develop the pulling strength needed to support lever progressions.",
      icon:        "💪",
      isMilestone: false,
      tips:        ["Focus on full range of motion", "Scapular pull-ups build foundation", "Add pauses at the top for strength"],
      requirements: [
        { type: "record_reps",    target: "pull_ups",   value: 5,   label: "5 Pull-Ups",     description: "Set a Pull-Up record of at least 5 reps" },
        { type: "record_seconds", target: "dead_hang",  value: 20,  label: "20s Dead Hang",  description: "Set a Dead Hang record of at least 20 seconds" },
      ],
      reward: { xp: 200, coins: 50, description: "Pull-Up Power unlocked" },
    },
    {
      id:          "fl_stage_3",
      stageNumber: 3,
      name:        "L-Sit Compression",
      description: "Compression strength is essential for front lever progression.",
      icon:        "📐",
      isMilestone: true,
      tips:        ["Compression strength is key", "Practice daily L-sit holds", "Hip flexor flexibility helps"],
      requirements: [
        { type: "record_reps", target: "pull_ups",   value: 10,  label: "10 Pull-Ups",   description: "Set a Pull-Up record of at least 10 reps" },
        { type: "level",       target: "",           value: 5,   label: "Level 5",        description: "Reach player level 5" },
        { type: "manual",      target: "l_sit_hold", value: 1,   label: "L-Sit Hold",     description: "Hold an L-sit position (self-verify)" },
      ],
      reward: { xp: 350, coins: 75, description: "L-Sit Compression unlocked" },
    },
    {
      id:          "fl_stage_4",
      stageNumber: 4,
      name:        "Tuck Front Lever",
      description: "First real front lever progression — body tucked, arms straight.",
      icon:        "🔄",
      isMilestone: true,
      tips:        ["Keep arms perfectly straight", "Engage lats hard", "Start with 1-2 second holds"],
      requirements: [
        { type: "record_reps",    target: "pull_ups",  value: 15,  label: "15 Pull-Ups",    description: "Set a Pull-Up record of at least 15 reps" },
        { type: "record_seconds", target: "dead_hang", value: 45,  label: "45s Dead Hang",  description: "Set a Dead Hang record of at least 45 seconds" },
        { type: "level",          target: "",          value: 8,   label: "Level 8",         description: "Reach player level 8" },
      ],
      reward: { xp: 500, coins: 100, titleId: "balance_adept", description: "Tuck Front Lever achieved" },
    },
    {
      id:          "fl_stage_5",
      stageNumber: 5,
      name:        "Advanced Tuck",
      description: "Open the hip angle to increase the lever difficulty.",
      icon:        "⚙️",
      isMilestone: false,
      tips:        ["Slowly open the hip angle", "Maintain body tension throughout", "Increase hold time gradually"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 20,   label: "20 Pull-Ups",  description: "Set a Pull-Up record of at least 20 reps" },
        { type: "xp",          target: "",         value: 2000, label: "2,000 XP",     description: "Earn at least 2,000 total XP" },
      ],
      reward: { xp: 750, coins: 150, description: "Advanced Tuck Front Lever achieved" },
    },
    {
      id:          "fl_stage_6",
      stageNumber: 6,
      name:        "Straddle Front Lever",
      description: "Legs out to the sides — harder than tuck, easier than full.",
      icon:        "🌟",
      isMilestone: false,
      tips:        ["Squeeze glutes and point toes", "Wide straddle is easier", "Slowly bring legs together"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 25,  label: "25 Pull-Ups",  description: "Set a Pull-Up record of at least 25 reps" },
        { type: "level",       target: "",         value: 15,  label: "Level 15",      description: "Reach player level 15" },
      ],
      reward: { xp: 1000, coins: 200, description: "Straddle Front Lever achieved" },
    },
    {
      id:          "fl_stage_7",
      stageNumber: 7,
      name:        "Full Front Lever",
      description: "The ultimate goal — body horizontal, arms straight, legs together.",
      icon:        "🏆",
      isMilestone: true,
      tips:        ["Full body tension from head to toe", "Practice with bands first", "3 seconds counts as a hold"],
      requirements: [
        { type: "record_reps", target: "pull_ups",         value: 30,  label: "30 Pull-Ups",       description: "Set a Pull-Up record of at least 30 reps" },
        { type: "level",       target: "",                 value: 20,  label: "Level 20",            description: "Reach player level 20" },
        { type: "manual",      target: "full_front_lever", value: 1,   label: "Full Front Lever",   description: "Hold a full front lever (self-verify)" },
      ],
      reward: { xp: 2000, coins: 500, titleId: "static_strength", description: "FULL FRONT LEVER ACHIEVED" },
    },
  ],
  completionReward: { xp: 3000, coins: 1000, titleId: "iron_will", description: "Front Lever Journey Complete!" },
};

const planche: JourneyDef = {
  id:             "planche",
  name:           "Planche Journey",
  subtitle:       "Conquering the Impossible Push",
  description:    "The full planche is one of the hardest skills in calisthenics. This journey builds the wrist, shoulder, and pushing strength over months of dedicated work.",
  icon:           "✈️",
  category:       "push",
  difficulty:     "legendary",
  estimatedWeeks: 24,
  featured:       true,
  tags:           ["push", "static", "strength", "planche", "advanced"],
  stages: [
    {
      id:          "pl_stage_1",
      stageNumber: 1,
      name:        "Wrist Preparation",
      description: "Planche places enormous stress on wrists — prepare them first.",
      icon:        "🖐️",
      isMilestone: false,
      tips:        ["Do daily wrist circles and stretches", "Build up time on hands gradually", "Never push through wrist pain"],
      requirements: [
        { type: "workout_count", target: "",         value: 3,   label: "3 Workouts",    description: "Log at least 3 workouts" },
        { type: "record_reps",   target: "push_ups", value: 10,  label: "10 Push-Ups",   description: "Set a Push-Up record of at least 10 reps" },
      ],
      reward: { xp: 100, coins: 25, description: "Wrist Preparation complete" },
    },
    {
      id:          "pl_stage_2",
      stageNumber: 2,
      name:        "Planche Lean",
      description: "Lean forward on hands to start loading the planche position.",
      icon:        "↗️",
      isMilestone: false,
      tips:        ["Lean as far forward as wrists allow", "Protract shoulders fully", "Hold for time — work up to 30s"],
      requirements: [
        { type: "record_reps", target: "push_ups", value: 20,  label: "20 Push-Ups",  description: "Set a Push-Up record of at least 20 reps" },
        { type: "level",       target: "",         value: 3,   label: "Level 3",       description: "Reach player level 3" },
      ],
      reward: { xp: 200, coins: 50, description: "Planche Lean mastered" },
    },
    {
      id:          "pl_stage_3",
      stageNumber: 3,
      name:        "Pseudo Planche Push-Ups",
      description: "Push-ups with leaned forward position — builds the exact strength needed.",
      icon:        "💪",
      isMilestone: true,
      tips:        ["More forward lean = harder", "Keep elbows in", "Add sets as strength increases"],
      requirements: [
        { type: "record_reps", target: "push_ups", value: 30,   label: "30 Push-Ups",  description: "Set a Push-Up record of at least 30 reps" },
        { type: "xp",          target: "",         value: 1000, label: "1,000 XP",     description: "Earn at least 1,000 total XP" },
      ],
      reward: { xp: 400, coins: 100, description: "Pseudo Planche Push-Ups mastered" },
    },
    {
      id:          "pl_stage_4",
      stageNumber: 4,
      name:        "Tuck Planche",
      description: "Both feet off the ground with tucked position — first real planche hold.",
      icon:        "🔄",
      isMilestone: true,
      tips:        ["Round the back to aid balance", "Squeeze everything tight", "Start with 1-second holds"],
      requirements: [
        { type: "record_reps", target: "push_ups",   value: 40,  label: "40 Push-Ups",    description: "Set a Push-Up record of at least 40 reps" },
        { type: "level",       target: "",           value: 12,  label: "Level 12",        description: "Reach player level 12" },
        { type: "manual",      target: "tuck_planche", value: 1, label: "Tuck Planche",   description: "Hold a tuck planche (self-verify)" },
      ],
      reward: { xp: 750, coins: 150, description: "Tuck Planche achieved" },
    },
    {
      id:          "pl_stage_5",
      stageNumber: 5,
      name:        "Advanced Tuck Planche",
      description: "Open the hip angle — halfway between tuck and straddle.",
      icon:        "⭐",
      isMilestone: false,
      tips:        ["Keep hips below shoulder height", "Slowly open hip angle", "Add push-up variations"],
      requirements: [
        { type: "level", target: "", value: 18,   label: "Level 18",   description: "Reach player level 18" },
        { type: "xp",    target: "", value: 5000, label: "5,000 XP",   description: "Earn at least 5,000 total XP" },
      ],
      reward: { xp: 1000, coins: 200, description: "Advanced Tuck Planche achieved" },
    },
    {
      id:          "pl_stage_6",
      stageNumber: 6,
      name:        "Straddle Planche",
      description: "Legs wide to the sides — significantly harder than tuck.",
      icon:        "🌟",
      isMilestone: false,
      tips:        ["Squeeze glutes and point toes", "Wide straddle first", "Work towards a 5s hold"],
      requirements: [
        { type: "level",  target: "",               value: 25, label: "Level 25",         description: "Reach player level 25" },
        { type: "manual", target: "straddle_planche", value: 1, label: "Straddle Planche", description: "Hold a straddle planche (self-verify)" },
      ],
      reward: { xp: 1500, coins: 300, description: "Straddle Planche achieved" },
    },
    {
      id:          "pl_stage_7",
      stageNumber: 7,
      name:        "Full Planche",
      description: "Body horizontal, arms straight, legs together. You have conquered gravity.",
      icon:        "👑",
      isMilestone: true,
      tips:        ["Must be 3+ seconds to count", "Record it for verification", "You are in the top 0.1%"],
      requirements: [
        { type: "level",  target: "",            value: 35, label: "Level 35",      description: "Reach player level 35" },
        { type: "manual", target: "full_planche", value: 1,  label: "Full Planche", description: "Hold a full planche (self-verify)" },
      ],
      reward: { xp: 3000, coins: 750, description: "FULL PLANCHE ACHIEVED" },
    },
  ],
  completionReward: { xp: 5000, coins: 2000, description: "Planche Journey Complete!" },
};

const handstand: JourneyDef = {
  id:             "handstand",
  name:           "Handstand Journey",
  subtitle:       "Balance Above the World",
  description:    "The freestanding handstand is an achievable goal for most athletes with dedicated practice. Build balance, strength, and body awareness.",
  icon:           "🤸",
  category:       "balance",
  difficulty:     "intermediate",
  estimatedWeeks: 8,
  featured:       false,
  tags:           ["balance", "handstand", "gymnastics", "beginner-friendly"],
  stages: [
    {
      id:          "hs_stage_1",
      stageNumber: 1,
      name:        "Wall Hold Foundation",
      description: "Start with wall-supported holds to build shoulder strength.",
      icon:        "🧱",
      isMilestone: false,
      tips:        ["Face away from wall (chest to wall)", "Keep core tight", "Work up to 60 second holds"],
      requirements: [
        { type: "workout_count", target: "", value: 2, label: "2 Workouts", description: "Log at least 2 workouts" },
      ],
      reward: { xp: 75, coins: 15, description: "Wall Hold Foundation complete" },
    },
    {
      id:          "hs_stage_2",
      stageNumber: 2,
      name:        "Wall Walk Mastery",
      description: "Walk your feet up the wall — fundamental for kick-up practice.",
      icon:        "🚶",
      isMilestone: false,
      tips:        ["Walk hands close to wall", "Breathe and stay calm", "Try to hold at the top"],
      requirements: [
        { type: "workout_count", target: "", value: 5, label: "5 Workouts", description: "Log at least 5 workouts" },
        { type: "level",         target: "", value: 2, label: "Level 2",    description: "Reach player level 2" },
      ],
      reward: { xp: 150, coins: 30, description: "Wall Walk Mastery achieved" },
    },
    {
      id:          "hs_stage_3",
      stageNumber: 3,
      name:        "Kick-Up Practice",
      description: "Start practicing kicking up to handstand against the wall.",
      icon:        "🦵",
      isMilestone: false,
      tips:        ["One leg kicks up first", "Second leg follows quickly", "Finger pressure controls balance"],
      requirements: [
        { type: "level",         target: "", value: 4,  label: "Level 4",    description: "Reach player level 4" },
        { type: "workout_count", target: "", value: 10, label: "10 Workouts", description: "Log at least 10 workouts" },
      ],
      reward: { xp: 250, coins: 50, description: "Kick-Up Practice mastered" },
    },
    {
      id:          "hs_stage_4",
      stageNumber: 4,
      name:        "Freestanding Attempts",
      description: "First attempts at holding a freestanding handstand.",
      icon:        "🤸",
      isMilestone: true,
      tips:        ["Set up near a wall for safety", "Use a spotter if possible", "Short holds (1-2s) count!"],
      requirements: [
        { type: "level",  target: "",              value: 6, label: "Level 6",             description: "Reach player level 6" },
        { type: "manual", target: "freestanding_hs", value: 1, label: "Freestanding HS Attempt", description: "Attempt a freestanding handstand (self-verify)" },
      ],
      reward: { xp: 400, coins: 80, description: "Freestanding Handstand attempted" },
    },
    {
      id:          "hs_stage_5",
      stageNumber: 5,
      name:        "10 Second Hold",
      description: "Hold a clean freestanding handstand for 10 seconds.",
      icon:        "⏱️",
      isMilestone: false,
      tips:        ["Film yourself for form check", "Micro-adjustments in fingers", "Straight body line is key"],
      requirements: [
        { type: "level",  target: "",       value: 8, label: "Level 8",      description: "Reach player level 8" },
        { type: "manual", target: "hs_10s", value: 1, label: "10s Handstand", description: "Hold a 10-second freestanding handstand (self-verify)" },
      ],
      reward: { xp: 600, coins: 120, description: "10 Second Handstand achieved" },
    },
    {
      id:          "hs_stage_6",
      stageNumber: 6,
      name:        "30 Second Hold",
      description: "Hold a clean freestanding handstand for 30 seconds.",
      icon:        "⏱️",
      isMilestone: true,
      tips:        ["Practice daily for 15-20 minutes", "Record from side for form check", "Relax the face and breathe"],
      requirements: [
        { type: "level",  target: "",       value: 12, label: "Level 12",     description: "Reach player level 12" },
        { type: "manual", target: "hs_30s", value: 1,  label: "30s Handstand", description: "Hold a 30-second freestanding handstand (self-verify)" },
      ],
      reward: { xp: 900, coins: 200, description: "30 Second Handstand achieved" },
    },
    {
      id:          "hs_stage_7",
      stageNumber: 7,
      name:        "60 Second Hold",
      description: "Hold a clean freestanding handstand for a full minute.",
      icon:        "🏆",
      isMilestone: true,
      tips:        ["At this level you can work on press handstands", "Try pirouette entries", "Explore one-arm attempts"],
      requirements: [
        { type: "level",  target: "",       value: 18, label: "Level 18",     description: "Reach player level 18" },
        { type: "manual", target: "hs_60s", value: 1,  label: "60s Handstand", description: "Hold a 60-second freestanding handstand (self-verify)" },
      ],
      reward: { xp: 1500, coins: 400, description: "60 Second Handstand — ELITE" },
    },
  ],
  completionReward: { xp: 2000, coins: 800, description: "Handstand Journey Complete!" },
};

const muscleUp: JourneyDef = {
  id:             "muscle_up",
  name:           "Muscle-Up Journey",
  subtitle:       "From Pull to Fly",
  description:    "The muscle-up is the gateway between pulling and pushing mastery. Combine explosive power with technical skill.",
  icon:           "🏋️",
  category:       "pull",
  difficulty:     "advanced",
  estimatedWeeks: 12,
  featured:       false,
  tags:           ["pull", "push", "explosive", "bar", "gymnastics"],
  stages: [
    {
      id:          "mu_stage_1",
      stageNumber: 1,
      name:        "Pulling Foundation",
      description: "Build the raw pulling strength required for muscle-up work.",
      icon:        "💪",
      isMilestone: false,
      tips:        ["Work on chest-to-bar pull-ups", "Add weight for extra strength", "Focus on the top range of motion"],
      requirements: [
        { type: "record_reps",   target: "pull_ups", value: 8,  label: "8 Pull-Ups",   description: "Set a Pull-Up record of at least 8 reps" },
        { type: "workout_count", target: "",         value: 10, label: "10 Workouts",  description: "Log at least 10 workouts" },
      ],
      reward: { xp: 150, coins: 30, description: "Pulling Foundation complete" },
    },
    {
      id:          "mu_stage_2",
      stageNumber: 2,
      name:        "High Pull-Ups",
      description: "Pull chin above the bar — chest-to-bar pull-ups build the transition strength.",
      icon:        "⬆️",
      isMilestone: false,
      tips:        ["Use a slight kip to learn the motion", "Keep elbows in", "Explode at the top"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 12, label: "12 Pull-Ups", description: "Set a Pull-Up record of at least 12 reps" },
        { type: "level",       target: "",         value: 6,  label: "Level 6",     description: "Reach player level 6" },
      ],
      reward: { xp: 250, coins: 60, description: "High Pull-Ups mastered" },
    },
    {
      id:          "mu_stage_3",
      stageNumber: 3,
      name:        "Kipping Practice",
      description: "Learn the hip drive to generate momentum for the muscle-up.",
      icon:        "🔄",
      isMilestone: true,
      tips:        ["Hip kip generates the momentum", "Time the kip with the pull", "Practice slow negatives"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 15,   label: "15 Pull-Ups",  description: "Set a Pull-Up record of at least 15 reps" },
        { type: "xp",          target: "",         value: 1500, label: "1,500 XP",     description: "Earn at least 1,500 total XP" },
      ],
      reward: { xp: 400, coins: 80, description: "Kipping Practice mastered" },
    },
    {
      id:          "mu_stage_4",
      stageNumber: 4,
      name:        "Negative Muscle-Up",
      description: "Jump above the bar and lower slowly — builds the exact strength needed.",
      icon:        "⬇️",
      isMilestone: false,
      tips:        ["Lower as slowly as possible (5-10 seconds)", "Control the transition", "Do 3-5 negatives per set"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 18,  label: "18 Pull-Ups",  description: "Set a Pull-Up record of at least 18 reps" },
        { type: "level",       target: "",         value: 10,  label: "Level 10",      description: "Reach player level 10" },
      ],
      reward: { xp: 600, coins: 120, description: "Negative Muscle-Up mastered" },
    },
    {
      id:          "mu_stage_5",
      stageNumber: 5,
      name:        "First Muscle-Up",
      description: "Your first full muscle-up. Even a kipping one counts — you crossed the bar!",
      icon:        "🏆",
      isMilestone: true,
      tips:        ["Celebrate this milestone!", "Clean up technique over time", "Strict comes later"],
      requirements: [
        { type: "level",  target: "",             value: 14, label: "Level 14",       description: "Reach player level 14" },
        { type: "manual", target: "first_muscle_up", value: 1, label: "First Muscle-Up", description: "Complete your first muscle-up (self-verify)" },
      ],
      reward: { xp: 1000, coins: 250, description: "FIRST MUSCLE-UP COMPLETE!" },
    },
    {
      id:          "mu_stage_6",
      stageNumber: 6,
      name:        "Clean Muscle-Up",
      description: "Strict, controlled muscle-up with minimal kip. True strength demonstrated.",
      icon:        "✨",
      isMilestone: false,
      tips:        ["Minimize the kip gradually", "Keep the bar close throughout", "Work on ring muscle-ups too"],
      requirements: [
        { type: "level",  target: "",              value: 18, label: "Level 18",        description: "Reach player level 18" },
        { type: "manual", target: "clean_muscle_up", value: 1, label: "Clean Muscle-Up", description: "Complete a clean muscle-up (self-verify)" },
      ],
      reward: { xp: 1500, coins: 350, description: "Clean Muscle-Up achieved" },
    },
  ],
  completionReward: { xp: 2500, coins: 1000, description: "Muscle-Up Journey Complete!" },
};

const humanFlag: JourneyDef = {
  id:             "human_flag",
  name:           "Human Flag Journey",
  subtitle:       "Lateral Strength to the Extreme",
  description:    "The human flag is the most visually stunning bodyweight skill. It requires exceptional lateral pushing and pulling strength.",
  icon:           "🚩",
  category:       "full_body",
  difficulty:     "legendary",
  estimatedWeeks: 20,
  featured:       true,
  tags:           ["full_body", "lateral", "strength", "flag", "advanced"],
  stages: [
    {
      id:          "hf_stage_1",
      stageNumber: 1,
      name:        "Lateral Pull Strength",
      description: "Build the asymmetric pulling and pushing strength base.",
      icon:        "↔️",
      isMilestone: false,
      tips:        ["Side plank holds are essential", "Train single-arm work", "Core rotation exercises help"],
      requirements: [
        { type: "record_reps",   target: "pull_ups", value: 15, label: "15 Pull-Ups",  description: "Set a Pull-Up record of at least 15 reps" },
        { type: "workout_count", target: "",         value: 20, label: "20 Workouts",  description: "Log at least 20 workouts" },
      ],
      reward: { xp: 150, coins: 35, description: "Lateral Pull Strength established" },
    },
    {
      id:          "hf_stage_2",
      stageNumber: 2,
      name:        "Side Plank Mastery",
      description: "Extended side planks build the lateral chain needed for the flag.",
      icon:        "📐",
      isMilestone: false,
      tips:        ["Work up to 60s each side", "Stack feet for harder variation", "Raise top arm overhead"],
      requirements: [
        { type: "level",          target: "",          value: 8,  label: "Level 8",      description: "Reach player level 8" },
        { type: "record_seconds", target: "dead_hang", value: 30, label: "30s Dead Hang", description: "Set a Dead Hang record of at least 30 seconds" },
      ],
      reward: { xp: 300, coins: 70, description: "Side Plank Mastery achieved" },
    },
    {
      id:          "hf_stage_3",
      stageNumber: 3,
      name:        "Vertical Flag Hold",
      description: "First flag progression — body vertical on the pole.",
      icon:        "🚩",
      isMilestone: true,
      tips:        ["Vertical is much easier than horizontal", "Top arm pushes, bottom arm pulls", "Build to 10s holds"],
      requirements: [
        { type: "level",  target: "",              value: 12,  label: "Level 12",        description: "Reach player level 12" },
        { type: "xp",     target: "",              value: 3000, label: "3,000 XP",       description: "Earn at least 3,000 total XP" },
        { type: "manual", target: "vertical_flag", value: 1,   label: "Vertical Flag",  description: "Hold a vertical flag position (self-verify)" },
      ],
      reward: { xp: 600, coins: 150, description: "Vertical Flag achieved" },
    },
    {
      id:          "hf_stage_4",
      stageNumber: 4,
      name:        "Tuck Human Flag",
      description: "Legs tucked, body horizontal — first real flag position.",
      icon:        "🔄",
      isMilestone: true,
      tips:        ["Keep the body as rigid as possible", "Top arm lock-out is critical", "1-2s counts as a hold"],
      requirements: [
        { type: "level",  target: "",          value: 18, label: "Level 18",    description: "Reach player level 18" },
        { type: "manual", target: "tuck_flag", value: 1,  label: "Tuck Flag",   description: "Hold a tuck human flag (self-verify)" },
      ],
      reward: { xp: 1000, coins: 250, description: "Tuck Human Flag achieved" },
    },
    {
      id:          "hf_stage_5",
      stageNumber: 5,
      name:        "Extended Flag",
      description: "One or both legs extended — approaching the full flag.",
      icon:        "🌟",
      isMilestone: false,
      tips:        ["One leg at a time is fine", "Squeeze everything tight", "Record for form verification"],
      requirements: [
        { type: "level",  target: "",               value: 25, label: "Level 25",       description: "Reach player level 25" },
        { type: "manual", target: "extended_flag",  value: 1,  label: "Extended Flag",  description: "Hold an extended flag position (self-verify)" },
      ],
      reward: { xp: 1500, coins: 350, description: "Extended Flag achieved" },
    },
    {
      id:          "hf_stage_6",
      stageNumber: 6,
      name:        "Full Human Flag",
      description: "Body perfectly horizontal, legs together. One of the rarest skills in existence.",
      icon:        "👑",
      isMilestone: true,
      tips:        ["3 second hold is the standard", "You are in elite company", "Film from the front for best view"],
      requirements: [
        { type: "level",  target: "",           value: 30, label: "Level 30",       description: "Reach player level 30" },
        { type: "manual", target: "full_flag",  value: 1,  label: "Full Human Flag", description: "Hold a full human flag (self-verify)" },
      ],
      reward: { xp: 3000, coins: 1000, description: "FULL HUMAN FLAG ACHIEVED" },
    },
  ],
  completionReward: { xp: 5000, coins: 2000, description: "Human Flag Journey Complete!" },
};

const oneArmPullup: JourneyDef = {
  id:             "one_arm_pullup",
  name:           "One Arm Pull-Up Journey",
  subtitle:       "The Ultimate Pulling Test",
  description:    "The one-arm pull-up is the holy grail of pulling strength. Only a tiny fraction of athletes ever achieve it.",
  icon:           "☝️",
  category:       "pull",
  difficulty:     "legendary",
  estimatedWeeks: 24,
  featured:       false,
  tags:           ["pull", "one-arm", "elite", "pulling-strength"],
  stages: [
    {
      id:          "oap_stage_1",
      stageNumber: 1,
      name:        "Weighted Pull-Ups",
      description: "Add external weight to build superhuman pulling strength.",
      icon:        "⚖️",
      isMilestone: false,
      tips:        ["Use a weight belt or vest", "Keep strict form with weight", "Work up to bodyweight +20%"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 20, label: "20 Pull-Ups", description: "Set a Pull-Up record of at least 20 reps" },
        { type: "level",       target: "",         value: 10, label: "Level 10",    description: "Reach player level 10" },
      ],
      reward: { xp: 200, coins: 50, description: "Weighted Pull-Up training begun" },
    },
    {
      id:          "oap_stage_2",
      stageNumber: 2,
      name:        "One Arm Negatives",
      description: "Jump to the top and lower slowly with one arm — builds single-arm strength.",
      icon:        "⬇️",
      isMilestone: false,
      tips:        ["Lower as slowly as possible", "Keep elbow in close", "Start with 5-10 seconds down"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 25, label: "25 Pull-Ups", description: "Set a Pull-Up record of at least 25 reps" },
        { type: "level",       target: "",         value: 15, label: "Level 15",    description: "Reach player level 15" },
      ],
      reward: { xp: 400, coins: 100, description: "One Arm Negatives mastered" },
    },
    {
      id:          "oap_stage_3",
      stageNumber: 3,
      name:        "Archer Pull-Ups",
      description: "One arm pulls while the other assists — transitional skill.",
      icon:        "🏹",
      isMilestone: true,
      tips:        ["Assist arm straight out to side", "Shift weight to working arm", "Gradually reduce assist"],
      requirements: [
        { type: "record_reps", target: "pull_ups", value: 30,   label: "30 Pull-Ups", description: "Set a Pull-Up record of at least 30 reps" },
        { type: "xp",          target: "",         value: 5000, label: "5,000 XP",    description: "Earn at least 5,000 total XP" },
      ],
      reward: { xp: 700, coins: 175, description: "Archer Pull-Ups mastered" },
    },
    {
      id:          "oap_stage_4",
      stageNumber: 4,
      name:        "Assisted One Arm",
      description: "Use a band or towel for minimal assistance on one-arm pull-ups.",
      icon:        "🤝",
      isMilestone: false,
      tips:        ["Use thinner bands over time", "Work each arm separately", "Aim for 3-5 assisted reps"],
      requirements: [
        { type: "level",  target: "",           value: 22, label: "Level 22",        description: "Reach player level 22" },
        { type: "manual", target: "assisted_oap", value: 1, label: "Assisted OAP",   description: "Complete an assisted one-arm pull-up (self-verify)" },
      ],
      reward: { xp: 1000, coins: 250, description: "Assisted One Arm Pull-Up achieved" },
    },
    {
      id:          "oap_stage_5",
      stageNumber: 5,
      name:        "First One Arm Pull-Up",
      description: "An unassisted one-arm pull-up. You have joined an elite group.",
      icon:        "🏆",
      isMilestone: true,
      tips:        ["Celebrate — this is extremely rare", "Film for proof!", "Clean up form over the next months"],
      requirements: [
        { type: "level",  target: "",          value: 28, label: "Level 28",         description: "Reach player level 28" },
        { type: "manual", target: "first_oap", value: 1,  label: "First One Arm PU", description: "Complete your first one-arm pull-up (self-verify)" },
      ],
      reward: { xp: 2000, coins: 500, description: "FIRST ONE ARM PULL-UP!" },
    },
    {
      id:          "oap_stage_6",
      stageNumber: 6,
      name:        "Clean One Arm Pull-Up",
      description: "Full range of motion, controlled, no body swing. Perfect form.",
      icon:        "✨",
      isMilestone: false,
      tips:        ["Dead hang start", "Full extension to chin above bar", "Practice both arms"],
      requirements: [
        { type: "level",  target: "",           value: 35, label: "Level 35",         description: "Reach player level 35" },
        { type: "manual", target: "clean_oap",  value: 1,  label: "Clean One Arm PU", description: "Complete a clean one-arm pull-up (self-verify)" },
      ],
      reward: { xp: 3000, coins: 750, description: "Clean One Arm Pull-Up achieved" },
    },
  ],
  completionReward: { xp: 6000, coins: 2500, description: "One Arm Pull-Up Journey Complete!" },
};

const pistolSquat: JourneyDef = {
  id:             "pistol_squat",
  name:           "Pistol Squat Journey",
  subtitle:       "Single Leg Strength Mastery",
  description:    "The pistol squat combines strength, flexibility, and balance into one impressive movement. Achievable for most with proper progressions.",
  icon:           "🦵",
  category:       "full_body",
  difficulty:     "intermediate",
  estimatedWeeks: 6,
  featured:       false,
  tags:           ["legs", "balance", "flexibility", "unilateral"],
  stages: [
    {
      id:          "ps_stage_1",
      stageNumber: 1,
      name:        "Squat Foundation",
      description: "Build the foundational squat pattern before adding single-leg work.",
      icon:        "🏋️",
      isMilestone: false,
      tips:        ["Full depth squats are key", "Ankle flexibility matters", "Goblet squats help alignment"],
      requirements: [
        { type: "workout_count", target: "", value: 3, label: "3 Workouts", description: "Log at least 3 workouts" },
      ],
      reward: { xp: 75, coins: 15, description: "Squat Foundation complete" },
    },
    {
      id:          "ps_stage_2",
      stageNumber: 2,
      name:        "Single Leg Balance",
      description: "Practice standing on one leg and build the stabilizing muscles.",
      icon:        "🦵",
      isMilestone: false,
      tips:        ["Stand on one leg while doing daily tasks", "Work on ankle mobility", "Hip stability exercises"],
      requirements: [
        { type: "level",         target: "", value: 3, label: "Level 3",     description: "Reach player level 3" },
        { type: "workout_count", target: "", value: 8, label: "8 Workouts",  description: "Log at least 8 workouts" },
      ],
      reward: { xp: 150, coins: 30, description: "Single Leg Balance developed" },
    },
    {
      id:          "ps_stage_3",
      stageNumber: 3,
      name:        "Assisted Pistol",
      description: "Use a support to practice the full range of motion.",
      icon:        "🤝",
      isMilestone: true,
      tips:        ["Hold a pole or TRX for balance", "Focus on depth first", "Both sides equally important"],
      requirements: [
        { type: "level",  target: "",              value: 5, label: "Level 5",          description: "Reach player level 5" },
        { type: "manual", target: "assisted_pistol", value: 1, label: "Assisted Pistol", description: "Complete an assisted pistol squat (self-verify)" },
      ],
      reward: { xp: 300, coins: 60, description: "Assisted Pistol Squat mastered" },
    },
    {
      id:          "ps_stage_4",
      stageNumber: 4,
      name:        "Negative Pistol",
      description: "Lower slowly on one leg — builds the eccentric strength needed.",
      icon:        "⬇️",
      isMilestone: false,
      tips:        ["Lower in 3-5 seconds", "Stand up with both legs", "Progress to step-down negatives"],
      requirements: [
        { type: "level",  target: "",               value: 7, label: "Level 7",          description: "Reach player level 7" },
        { type: "manual", target: "negative_pistol", value: 1, label: "Negative Pistol", description: "Complete a negative pistol squat (self-verify)" },
      ],
      reward: { xp: 450, coins: 90, description: "Negative Pistol Squat mastered" },
    },
    {
      id:          "ps_stage_5",
      stageNumber: 5,
      name:        "Full Pistol Squat",
      description: "Unassisted pistol squat to full depth. Impressive single-leg strength.",
      icon:        "🏆",
      isMilestone: true,
      tips:        ["Arms forward for counterbalance", "Heel must stay on floor", "Control the descent"],
      requirements: [
        { type: "level",  target: "",             value: 10, label: "Level 10",       description: "Reach player level 10" },
        { type: "manual", target: "pistol_squat", value: 1,  label: "Full Pistol Squat", description: "Complete a full pistol squat (self-verify)" },
      ],
      reward: { xp: 750, coins: 200, description: "FULL PISTOL SQUAT ACHIEVED!" },
    },
  ],
  completionReward: { xp: 1000, coins: 400, description: "Pistol Squat Journey Complete!" },
};

const lSit: JourneyDef = {
  id:             "l_sit",
  name:           "L-Sit Journey",
  subtitle:       "Core Compression Mastery",
  description:    "The L-sit is a fundamental skill that builds incredible core and hip flexor strength. An essential foundation for advanced calisthenics.",
  icon:           "📐",
  category:       "core",
  difficulty:     "beginner",
  estimatedWeeks: 4,
  featured:       false,
  tags:           ["core", "compression", "beginner", "fundamentals"],
  stages: [
    {
      id:          "ls_stage_1",
      stageNumber: 1,
      name:        "Compression Work",
      description: "Start building the hip flexor and core strength with seated compression.",
      icon:        "📐",
      isMilestone: false,
      tips:        ["Practice seated compression daily", "Stretch hamstrings", "Build hip flexor endurance"],
      requirements: [
        { type: "workout_count", target: "", value: 2, label: "2 Workouts", description: "Log at least 2 workouts" },
      ],
      reward: { xp: 50, coins: 10, description: "Compression Work begun" },
    },
    {
      id:          "ls_stage_2",
      stageNumber: 2,
      name:        "Tuck L-Sit",
      description: "Both legs tucked while elevated — first suspension skill.",
      icon:        "🔄",
      isMilestone: false,
      tips:        ["Use parallel bars or push-up handles", "Protract shoulders down", "Hold for 3-5 seconds initially"],
      requirements: [
        { type: "level",         target: "", value: 2, label: "Level 2",    description: "Reach player level 2" },
        { type: "workout_count", target: "", value: 5, label: "5 Workouts", description: "Log at least 5 workouts" },
      ],
      reward: { xp: 100, coins: 25, description: "Tuck L-Sit achieved" },
    },
    {
      id:          "ls_stage_3",
      stageNumber: 3,
      name:        "L-Sit Attempt",
      description: "First attempts at extending one or both legs in the L-sit position.",
      icon:        "💪",
      isMilestone: true,
      tips:        ["One leg out at a time is fine", "Keep legs parallel to floor", "Point the toes"],
      requirements: [
        { type: "level",  target: "",          value: 4, label: "Level 4",       description: "Reach player level 4" },
        { type: "manual", target: "l_sit_5s",  value: 1, label: "L-Sit 5s",     description: "Hold an L-sit for 5 seconds (self-verify)" },
      ],
      reward: { xp: 200, coins: 50, description: "L-Sit Attempt successful" },
    },
    {
      id:          "ls_stage_4",
      stageNumber: 4,
      name:        "10 Second L-Sit",
      description: "Hold the L-sit position for 10 seconds clean.",
      icon:        "⏱️",
      isMilestone: false,
      tips:        ["Practice 3x5s then work up", "Accumulate time across sets", "Daily practice is key"],
      requirements: [
        { type: "level",  target: "",           value: 6, label: "Level 6",   description: "Reach player level 6" },
        { type: "manual", target: "l_sit_10s",  value: 1, label: "L-Sit 10s", description: "Hold an L-sit for 10 seconds (self-verify)" },
      ],
      reward: { xp: 300, coins: 75, description: "10 Second L-Sit achieved" },
    },
    {
      id:          "ls_stage_5",
      stageNumber: 5,
      name:        "30 Second L-Sit",
      description: "30 second L-sit hold — a significant achievement and strength indicator.",
      icon:        "🏆",
      isMilestone: true,
      tips:        ["This is the standard benchmark", "Now work on V-sit and other progressions", "Add to warm-up routine"],
      requirements: [
        { type: "level",  target: "",           value: 8, label: "Level 8",    description: "Reach player level 8" },
        { type: "manual", target: "l_sit_30s",  value: 1, label: "L-Sit 30s", description: "Hold an L-sit for 30 seconds (self-verify)" },
      ],
      reward: { xp: 500, coins: 150, description: "30 Second L-Sit — MASTERED!" },
    },
  ],
  completionReward: { xp: 750, coins: 300, description: "L-Sit Journey Complete!" },
};

// ─── Exports ──────────────────────────────────────────────────────────────────

export const ALL_JOURNEYS: JourneyDef[] = [
  frontLever, planche, handstand, muscleUp, humanFlag, oneArmPullup, pistolSquat, lSit,
];

export const JOURNEY_MAP: Record<string, JourneyDef> = Object.fromEntries(
  ALL_JOURNEYS.map((j) => [j.id, j])
);

export const FEATURED_JOURNEYS: JourneyDef[] = ALL_JOURNEYS.filter((j) => j.featured);

export const JOURNEY_DIFFICULTY_META: Record<JourneyDifficulty, {
  label: string; color: string; border: string; bg: string; icon: string;
}> = {
  beginner:     { label: "Beginner",     color: "text-green-400",  border: "border-green-500/30",  bg: "bg-green-500/10",  icon: "🌱" },
  intermediate: { label: "Intermediate", color: "text-sky-400",    border: "border-sky-500/30",    bg: "bg-sky-500/10",    icon: "⚡" },
  advanced:     { label: "Advanced",     color: "text-orange-400", border: "border-orange-500/30", bg: "bg-orange-500/10", icon: "🔥" },
  elite:        { label: "Elite",        color: "text-purple-400", border: "border-purple-500/30", bg: "bg-purple-500/10", icon: "👑" },
  legendary:    { label: "Legendary",    color: "text-yellow-400", border: "border-yellow-500/40", bg: "bg-yellow-500/10", icon: "🌟" },
};
