import { LibrarySkill, ProgressionChain } from "./library-types";

export const PROGRESSION_CHAINS: ProgressionChain[] = [
  {
    id: "push_chain",
    name: "Push Progression",
    icon: "💪",
    skills: ["push_up", "diamond_push_up", "archer_push_up", "pseudo_planche_push_up", "one_arm_push_up"],
    description: "From basic push-ups to one-arm mastery",
  },
  {
    id: "pull_chain",
    name: "Pull Progression",
    icon: "🔼",
    skills: ["dead_hang", "scapular_pull", "pull_up", "chest_to_bar", "explosive_pull_up", "muscle_up", "ring_muscle_up"],
    description: "From dead hangs to ring muscle-ups",
  },
  {
    id: "front_lever_chain",
    name: "Front Lever Path",
    icon: "🎯",
    skills: ["dead_hang", "pull_up", "l_sit", "tuck_front_lever", "adv_tuck_front_lever", "straddle_front_lever", "full_front_lever"],
    description: "The complete front lever progression",
  },
  {
    id: "planche_chain",
    name: "Planche Path",
    icon: "👐",
    skills: ["push_up", "planche_lean", "pseudo_planche_push_up", "tuck_planche", "adv_tuck_planche", "straddle_planche", "full_planche"],
    description: "From push-ups to the full planche",
  },
  {
    id: "handstand_chain",
    name: "Handstand Path",
    icon: "🤸",
    skills: ["wall_handstand", "wall_walk", "kick_up_practice", "freestanding_handstand", "handstand_push_up", "press_handstand", "one_arm_handstand"],
    description: "Wall holds to one-arm handstand",
  },
  {
    id: "human_flag_chain",
    name: "Human Flag Path",
    icon: "🚩",
    skills: ["pull_up", "side_plank", "vertical_flag", "tuck_human_flag", "extended_human_flag", "full_human_flag"],
    description: "The complete human flag journey",
  },
  {
    id: "core_chain",
    name: "Core Compression Path",
    icon: "📐",
    skills: ["hollow_body", "tuck_l_sit", "l_sit", "v_sit", "manna"],
    description: "From hollow body to the manna",
  },
  {
    id: "leg_chain",
    name: "Leg Strength Path",
    icon: "🦵",
    skills: ["squat", "pistol_squat_negative", "pistol_squat", "shrimp_squat", "dragon_squat"],
    description: "From squats to advanced single-leg work",
  },
];

export const LIBRARY_SKILLS: LibrarySkill[] = [
  // ─── BEGINNER ────────────────────────────────────────────────────────────────
  {
    id: "push_up",
    name: "Push-Up",
    icon: "💪",
    tier: "beginner",
    domain: "push",
    description: "The foundation of all pushing movements.",
    purpose: "Builds chest, shoulder and tricep strength with full body tension.",
    benefits: ["Universal pushing foundation", "Accessible anywhere", "Trains full-body tension", "Scales easily"],
    commonMistakes: ["Flared elbows", "Sagging hips", "Partial range of motion", "Head forward"],
    prerequisites: [],
    progressions: ["diamond_push_up", "archer_push_up"],
    regressions: ["incline_push_up"],
    relatedSkills: ["planche_lean", "pseudo_planche_push_up"],
    masteryCategories: ["strength"],
    coachingTips: ["Keep core tight throughout", "Full ROM every rep", "Scapular protraction at top"],
    isLegendary: false,
    tags: ["beginner", "push", "foundation"],
  },
  {
    id: "pull_up",
    name: "Pull-Up",
    icon: "🔼",
    tier: "beginner",
    domain: "pull",
    description: "Master the vertical pull.",
    purpose: "Develops lat, bicep and scapular strength for all pulling skills.",
    benefits: ["Foundation for all pull skills", "Excellent lat developer", "Builds grip strength", "Scalable to many variations"],
    commonMistakes: ["Incomplete dead hang start", "Kipping without strength base", "Not clearing chin over bar", "Neglecting scapular engagement"],
    prerequisites: [],
    progressions: ["chest_to_bar", "explosive_pull_up", "archer_pull_up"],
    regressions: ["scapular_pull", "dead_hang"],
    relatedSkills: ["muscle_up", "front_lever"],
    journeyId: "pull_up",
    masteryCategories: ["strength", "grip"],
    coachingTips: ["Dead hang start every rep", "Retract scapula before pulling", "Controlled eccentric"],
    isLegendary: false,
    tags: ["beginner", "pull", "foundation"],
  },
  {
    id: "dead_hang",
    name: "Dead Hang",
    icon: "🧱",
    tier: "beginner",
    domain: "pull",
    description: "The foundation of grip and shoulder health.",
    purpose: "Builds grip endurance, shoulder health and connective tissue.",
    benefits: ["Decompresses the spine", "Builds grip endurance", "Essential shoulder health", "Pre-requisite for all bar work"],
    commonMistakes: ["Shrugged shoulders", "Holding breath", "Bent arms", "Neglecting it as 'too easy'"],
    prerequisites: [],
    progressions: ["scapular_pull", "pull_up"],
    regressions: [],
    relatedSkills: ["pull_up", "front_lever"],
    masteryCategories: ["grip", "strength"],
    coachingTips: ["Shoulders fully relaxed", "Breathe steadily", "Build to 60 seconds"],
    isLegendary: false,
    tags: ["beginner", "pull", "grip", "foundation"],
  },
  {
    id: "hollow_body",
    name: "Hollow Body Hold",
    icon: "🌊",
    tier: "beginner",
    domain: "core",
    description: "The foundation of all advanced skills.",
    purpose: "Develops core compression and body tension critical for all gymnastics skills.",
    benefits: ["Foundation for planche and front lever", "Builds core compression", "Teaches body tension", "Improves all calisthenics"],
    commonMistakes: ["Lower back not pressed to floor", "Toes not pointed", "Holding breath", "Bent arms or legs"],
    prerequisites: [],
    progressions: ["tuck_l_sit", "l_sit"],
    regressions: ["plank"],
    relatedSkills: ["l_sit", "dragon_flag", "front_lever"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Press lower back into floor", "Point toes", "Arms overhead for harder version"],
    isLegendary: false,
    tags: ["beginner", "core", "foundation"],
  },
  {
    id: "squat",
    name: "Deep Squat",
    icon: "🏋️",
    tier: "beginner",
    domain: "legs",
    description: "Full depth squat with good form.",
    purpose: "Builds bilateral leg strength and ankle/hip mobility.",
    benefits: ["Full lower body strength", "Hip and ankle mobility", "Foundation for pistol squat", "Functional movement pattern"],
    commonMistakes: ["Heels rising", "Chest collapsing", "Knees caving", "Shallow depth"],
    prerequisites: [],
    progressions: ["pistol_squat_negative", "pistol_squat"],
    regressions: [],
    relatedSkills: ["pistol_squat", "shrimp_squat"],
    masteryCategories: ["strength", "mobility"],
    coachingTips: ["Heels flat on floor", "Chest up throughout", "Full depth below parallel"],
    isLegendary: false,
    tags: ["beginner", "legs", "foundation"],
  },
  {
    id: "wall_handstand",
    name: "Wall Handstand",
    icon: "🧱",
    tier: "beginner",
    domain: "balance",
    description: "Handstand with wall support.",
    purpose: "Builds wrist and shoulder strength, introduces inversion.",
    benefits: ["Safe introduction to inversion", "Builds wrist strength", "Shoulder conditioning", "Foundation for freestanding work"],
    commonMistakes: ["Banana back", "Wrists not aligned under shoulders", "Looking at wall", "Not engaging core"],
    prerequisites: [],
    progressions: ["wall_walk", "kick_up_practice"],
    regressions: [],
    relatedSkills: ["freestanding_handstand", "handstand_push_up"],
    masteryCategories: ["balance", "strength"],
    coachingTips: ["Straight body line", "Push the floor away", "Core tight throughout"],
    isLegendary: false,
    tags: ["beginner", "balance", "inversion"],
  },
  {
    id: "side_plank",
    name: "Side Plank",
    icon: "📐",
    tier: "beginner",
    domain: "core",
    description: "Lateral core stability hold.",
    purpose: "Builds lateral core strength needed for human flag.",
    benefits: ["Lateral core strength", "Shoulder stability", "Human flag prerequisite", "Oblique development"],
    commonMistakes: ["Hip sag", "Shoulder blade collapsing", "Neck misalignment", "Too short duration"],
    prerequisites: [],
    progressions: ["vertical_flag", "tuck_human_flag"],
    regressions: ["plank"],
    relatedSkills: ["human_flag", "full_human_flag"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Hips stacked vertically", "Push into the floor", "Build to 60 seconds each side"],
    isLegendary: false,
    tags: ["beginner", "core", "lateral"],
  },
  {
    id: "plank",
    name: "Plank",
    icon: "▬",
    tier: "beginner",
    domain: "core",
    description: "Isometric core stability hold.",
    purpose: "Builds core endurance and body tension fundamentals.",
    benefits: ["Core endurance", "Body tension foundation", "Easy to progress", "Accessible anywhere"],
    commonMistakes: ["Hip piking or sagging", "Elbow position wrong", "Breath holding", "Rushing to harder variations"],
    prerequisites: [],
    progressions: ["hollow_body", "side_plank"],
    regressions: [],
    relatedSkills: ["hollow_body", "l_sit"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Neutral spine", "Glutes squeezed", "Build to 2 minutes"],
    isLegendary: false,
    tags: ["beginner", "core"],
  },
  {
    id: "bridge_basic",
    name: "Basic Bridge",
    icon: "🌉",
    tier: "beginner",
    domain: "mobility",
    description: "Supine back bridge for spinal mobility.",
    purpose: "Develops thoracic extension and shoulder flexibility.",
    benefits: ["Spinal mobility", "Shoulder flexibility", "Counter to sitting", "Foundation for advanced bridges"],
    commonMistakes: ["Feet too far from hips", "Neck compression", "Not extending hips fully", "Limited shoulder opening"],
    prerequisites: [],
    progressions: ["wall_walk"],
    regressions: [],
    relatedSkills: ["press_handstand"],
    masteryCategories: ["mobility"],
    coachingTips: ["Push hips up fully", "Arms straight", "Chest toward chin"],
    isLegendary: false,
    tags: ["beginner", "mobility", "bridge"],
  },
  {
    id: "tuck_l_sit",
    name: "Tuck L-Sit",
    icon: "🦅",
    tier: "beginner",
    domain: "core",
    description: "L-sit with knees tucked to chest.",
    purpose: "Introduction to compression and straight-arm support.",
    benefits: ["Compression strength foundation", "Wrist conditioning", "Shoulder depression", "First step to L-sit"],
    commonMistakes: ["Elbows bent", "Shoulders shrugged", "Feet touching ground", "Insufficient arm lockout"],
    prerequisites: [],
    progressions: ["l_sit"],
    regressions: ["plank"],
    relatedSkills: ["l_sit", "v_sit"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Lock the elbows", "Depress shoulders hard", "Hold 3-5 seconds at first"],
    isLegendary: false,
    tags: ["beginner", "core", "compression"],
  },

  // ─── INTERMEDIATE ─────────────────────────────────────────────────────────────
  {
    id: "diamond_push_up",
    name: "Diamond Push-Up",
    icon: "💎",
    tier: "intermediate",
    domain: "push",
    description: "Close-grip push-up with hands forming diamond.",
    purpose: "Shifts load to triceps and inner chest.",
    benefits: ["Tricep isolation", "Inner chest development", "OAPU preparation", "Grip variation"],
    commonMistakes: ["Too wide elbow flare", "Hands not centered", "Partial range", "Hip sag"],
    prerequisites: ["push_up"],
    progressions: ["archer_push_up"],
    regressions: ["push_up"],
    relatedSkills: ["one_arm_push_up"],
    masteryCategories: ["strength"],
    coachingTips: ["Elbows track back", "Full chest to hands", "Same tension as regular push-up"],
    isLegendary: false,
    tags: ["intermediate", "push", "tricep"],
  },
  {
    id: "archer_push_up",
    name: "Archer Push-Up",
    icon: "🏹",
    tier: "intermediate",
    domain: "push",
    description: "Unilateral pushing with extended arm.",
    purpose: "Bridges gap between push-up and one-arm push-up.",
    benefits: ["Unilateral strength", "OAP preparation", "Wider ROM", "Chest development"],
    commonMistakes: ["Rotating the hips", "Weak side collapse", "Insufficient lean", "Rushing progression"],
    prerequisites: ["push_up"],
    progressions: ["pseudo_planche_push_up", "one_arm_push_up"],
    regressions: ["diamond_push_up"],
    relatedSkills: ["one_arm_push_up"],
    masteryCategories: ["strength"],
    coachingTips: ["Keep core tight", "Slow controlled movement", "Equal depth both sides"],
    isLegendary: false,
    tags: ["intermediate", "push", "unilateral"],
  },
  {
    id: "scapular_pull",
    name: "Scapular Pull-Up",
    icon: "🦴",
    tier: "intermediate",
    domain: "pull",
    description: "Scapular depression without elbow bend.",
    purpose: "Trains scapular muscles essential for front lever and muscle-up.",
    benefits: ["Scapular strength", "Shoulder health", "Lat activation", "Injury prevention"],
    commonMistakes: ["Elbow bending", "Arching back", "Insufficient elevation", "Too fast"],
    prerequisites: ["dead_hang"],
    progressions: ["pull_up"],
    regressions: ["dead_hang"],
    relatedSkills: ["pull_up", "front_lever"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Straight arms throughout", "Feel the shoulder blades move", "Slow and controlled"],
    isLegendary: false,
    tags: ["intermediate", "pull", "scapular"],
  },
  {
    id: "chest_to_bar",
    name: "Chest-to-Bar Pull-Up",
    icon: "⬆️",
    tier: "intermediate",
    domain: "pull",
    description: "Pull-up with chest touching the bar.",
    purpose: "Develops greater pulling range for muscle-up transition.",
    benefits: ["Greater pulling range", "Muscle-up preparation", "Upper back development", "Stronger grip"],
    commonMistakes: ["Kipping instead of strength", "Only chin clearing bar", "Not touching chest", "Poor scapular control"],
    prerequisites: ["pull_up"],
    progressions: ["explosive_pull_up", "muscle_up"],
    regressions: ["pull_up"],
    relatedSkills: ["muscle_up", "ring_muscle_up"],
    masteryCategories: ["strength", "grip"],
    coachingTips: ["Focus on lat engagement", "Retract scapula", "Aim for sternum to bar"],
    isLegendary: false,
    tags: ["intermediate", "pull", "advanced-pull"],
  },
  {
    id: "explosive_pull_up",
    name: "Explosive Pull-Up",
    icon: "💥",
    tier: "intermediate",
    domain: "pull",
    description: "Pull-up with explosive power to clear hands off bar.",
    purpose: "Builds the explosive power needed for muscle-up.",
    benefits: ["Explosive pulling power", "Fast-twitch lat development", "Muscle-up prerequisite", "Athletic power"],
    commonMistakes: ["Insufficient base strength", "Not using full pull", "Landing wrong", "Kipping to compensate"],
    prerequisites: ["pull_up"],
    progressions: ["muscle_up"],
    regressions: ["chest_to_bar"],
    relatedSkills: ["muscle_up"],
    masteryCategories: ["strength", "explosiveness"],
    coachingTips: ["Max pull-ups first", "Explosive intent every rep", "Straight arms at top"],
    isLegendary: false,
    tags: ["intermediate", "pull", "explosive"],
  },
  {
    id: "l_sit",
    name: "L-Sit",
    icon: "📐",
    tier: "intermediate",
    domain: "core",
    description: "Compress your legs to parallel while supporting yourself.",
    purpose: "Develops hip flexor and compression strength for advanced skills.",
    benefits: ["Hip flexor strength", "Compression foundation", "Wrist conditioning", "Core strength"],
    commonMistakes: ["Bent knees", "Bent elbows", "Shrugged shoulders", "Not maintaining position"],
    prerequisites: ["tuck_l_sit", "hollow_body"],
    progressions: ["v_sit"],
    regressions: ["tuck_l_sit"],
    relatedSkills: ["v_sit", "manna"],
    journeyId: "l_sit",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Tuck first then extend", "Compression work daily", "Parallel bars easier than floor"],
    isLegendary: false,
    tags: ["intermediate", "core", "compression"],
  },
  {
    id: "pistol_squat",
    name: "Pistol Squat",
    icon: "🦵",
    tier: "intermediate",
    domain: "legs",
    description: "Single-leg full depth squat.",
    purpose: "Builds unilateral leg strength and balance.",
    benefits: ["Unilateral strength", "Balance and proprioception", "Hip mobility", "No equipment needed"],
    commonMistakes: ["Heel rising", "Torso collapse", "Knee caving inward", "Using support to cheat"],
    prerequisites: ["squat", "pistol_squat_negative"],
    progressions: ["shrimp_squat"],
    regressions: ["pistol_squat_negative"],
    relatedSkills: ["shrimp_squat", "dragon_squat"],
    journeyId: "pistol_squat",
    masteryCategories: ["strength", "mobility", "balance"],
    coachingTips: ["Heel elevated helps initially", "Hip mobility is critical", "Counterbalance with arms"],
    isLegendary: false,
    tags: ["intermediate", "legs", "unilateral"],
  },
  {
    id: "pistol_squat_negative",
    name: "Pistol Squat Negative",
    icon: "⬇️",
    tier: "intermediate",
    domain: "legs",
    description: "Slow eccentric single-leg squat.",
    purpose: "Builds eccentric strength for the full pistol squat.",
    benefits: ["Eccentric strength", "Safe progression", "Balance training", "Tendon conditioning"],
    commonMistakes: ["Going too fast", "Using support throughout", "Jumping up instead of returning", "Skipping ankle mobility"],
    prerequisites: ["squat"],
    progressions: ["pistol_squat"],
    regressions: ["squat"],
    relatedSkills: ["pistol_squat"],
    masteryCategories: ["strength", "mobility"],
    coachingTips: ["5 second descent", "Keep heel planted", "Use support only when needed"],
    isLegendary: false,
    tags: ["intermediate", "legs", "eccentric"],
  },
  {
    id: "wall_walk",
    name: "Wall Walk",
    icon: "🧗",
    tier: "intermediate",
    domain: "balance",
    description: "Walk hands and feet toward wall into handstand.",
    purpose: "Builds shoulder strength and comfort with inversion.",
    benefits: ["Shoulder conditioning", "Inversion comfort", "Handstand preparation", "Core strength"],
    commonMistakes: ["Too fast", "Banana back at top", "Hands too far from wall", "Collapsing at shoulders"],
    prerequisites: ["wall_handstand"],
    progressions: ["kick_up_practice"],
    regressions: ["wall_handstand"],
    relatedSkills: ["freestanding_handstand"],
    masteryCategories: ["balance", "strength"],
    coachingTips: ["Slow and controlled", "Reach full extension", "Straight body at top"],
    isLegendary: false,
    tags: ["intermediate", "balance", "handstand"],
  },
  {
    id: "kick_up_practice",
    name: "Kick-Up Practice",
    icon: "🦶",
    tier: "intermediate",
    domain: "balance",
    description: "Practicing kicking up to handstand without wall.",
    purpose: "Develops entry technique for freestanding handstand.",
    benefits: ["Entry technique", "Balance finding", "Kick control", "Psychological confidence"],
    commonMistakes: ["Over-kicking", "Under-kicking", "Wrong hand position", "Fear-based hesitation"],
    prerequisites: ["wall_walk"],
    progressions: ["freestanding_handstand"],
    regressions: ["wall_walk"],
    relatedSkills: ["freestanding_handstand"],
    masteryCategories: ["balance", "coordination"],
    coachingTips: ["One leg kicks, one follows", "Look at hands", "Find balance point gradually"],
    isLegendary: false,
    tags: ["intermediate", "balance", "handstand"],
  },
  {
    id: "freestanding_handstand",
    name: "Freestanding Handstand",
    icon: "🤸",
    tier: "intermediate",
    domain: "balance",
    description: "Hold a freestanding handstand for 5+ seconds.",
    purpose: "Develops balance mastery and shoulder stability.",
    benefits: ["Balance mastery", "Shoulder strength", "Core control", "Foundation for HSPU and press"],
    commonMistakes: ["Over-relying on banana back", "Finger pressure ignored", "Not building hold time", "Insufficient daily practice"],
    prerequisites: ["kick_up_practice"],
    progressions: ["handstand_push_up", "press_handstand", "one_arm_handstand"],
    regressions: ["kick_up_practice", "wall_walk"],
    relatedSkills: ["handstand_push_up", "press_handstand"],
    journeyId: "handstand",
    masteryCategories: ["balance", "strength"],
    coachingTips: ["Wall work daily", "Finger pressure for balance", "Straight body is king"],
    isLegendary: false,
    tags: ["intermediate", "balance", "handstand"],
  },
  {
    id: "planche_lean",
    name: "Planche Lean",
    icon: "↗️",
    tier: "intermediate",
    domain: "static",
    description: "Lean forward on straight arms with feet still grounded.",
    purpose: "Introduces planche-specific shoulder load.",
    benefits: ["Planche preparation", "Wrist conditioning", "Shoulder strength", "Safe loading"],
    commonMistakes: ["Insufficient forward lean", "Wrists unprepared", "Bent elbows", "Neglecting daily practice"],
    prerequisites: ["push_up"],
    progressions: ["pseudo_planche_push_up", "tuck_planche"],
    regressions: ["push_up"],
    relatedSkills: ["tuck_planche", "full_planche"],
    journeyId: "planche",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Wrist preparation is crucial", "Forward lean angle matters", "Scapular depression"],
    isLegendary: false,
    tags: ["intermediate", "push", "planche"],
  },
  {
    id: "pseudo_planche_push_up",
    name: "Pseudo Planche Push-Up",
    icon: "🔄",
    tier: "intermediate",
    domain: "push",
    description: "Push-up with hands at hips in planche lean position.",
    purpose: "Builds planche-specific push strength.",
    benefits: ["Planche-specific strength", "Wrist conditioning", "Tricep strength", "Shoulder strength"],
    commonMistakes: ["Hands too far forward", "Insufficient lean", "Hips rising", "Full ROM neglected"],
    prerequisites: ["planche_lean"],
    progressions: ["tuck_planche"],
    regressions: ["planche_lean"],
    relatedSkills: ["tuck_planche"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Lean forward before pushing", "Full ROM", "Slow eccentric"],
    isLegendary: false,
    tags: ["intermediate", "push", "planche"],
  },
  {
    id: "tuck_front_lever",
    name: "Tuck Front Lever",
    icon: "🎯",
    tier: "intermediate",
    domain: "pull",
    description: "Front lever hold with legs tucked.",
    purpose: "First step in the front lever progression.",
    benefits: ["Front lever introduction", "Lat strength", "Scapular depression", "Body tension"],
    commonMistakes: ["Legs not tucked tightly", "Bent arms", "Not horizontal", "Shrugged shoulders"],
    prerequisites: ["pull_up", "dead_hang"],
    progressions: ["adv_tuck_front_lever"],
    regressions: ["scapular_pull"],
    relatedSkills: ["full_front_lever"],
    journeyId: "front_lever",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Depress and retract scapula", "Arms straight", "Horizontal is the goal"],
    isLegendary: false,
    tags: ["intermediate", "pull", "front-lever"],
  },
  {
    id: "vertical_flag",
    name: "Vertical Flag",
    icon: "🚩",
    tier: "intermediate",
    domain: "static",
    description: "Body held vertically on a pole.",
    purpose: "First step in the human flag progression.",
    benefits: ["Flag introduction", "Lateral strength", "Grip strength", "Shoulder conditioning"],
    commonMistakes: ["Not fully straight", "Insufficient push-pull", "Wrong pole grip", "Body not aligned"],
    prerequisites: ["pull_up", "side_plank"],
    progressions: ["tuck_human_flag"],
    regressions: ["side_plank"],
    relatedSkills: ["full_human_flag"],
    journeyId: "human_flag",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Push with bottom arm", "Pull with top arm", "Straight body line"],
    isLegendary: false,
    tags: ["intermediate", "static", "human-flag"],
  },
  {
    id: "muscle_up",
    name: "Muscle-Up",
    icon: "🔝",
    tier: "intermediate",
    domain: "pull",
    description: "Classic transition from pull to dip above the bar.",
    purpose: "Combines pulling and pushing in one explosive movement.",
    benefits: ["Explosive full body strength", "Transition training", "Upper body power", "Athletic expression"],
    commonMistakes: ["Kipping without base strength", "Not completing the dip", "Missing the false grip", "Chest not over bar"],
    prerequisites: ["pull_up", "chest_to_bar", "explosive_pull_up"],
    progressions: ["ring_muscle_up"],
    regressions: ["explosive_pull_up"],
    relatedSkills: ["ring_muscle_up"],
    journeyId: "muscle_up",
    masteryCategories: ["strength", "explosiveness"],
    coachingTips: ["Master the kip first", "Explosive pull required", "Transition is the key"],
    isLegendary: false,
    tags: ["intermediate", "pull", "explosive"],
  },
  {
    id: "v_sit",
    name: "V-Sit",
    icon: "✌️",
    tier: "intermediate",
    domain: "core",
    description: "L-sit with legs elevated above parallel.",
    purpose: "Advanced compression requiring hip flexor and core strength.",
    benefits: ["Extreme hip flexor strength", "Compression mastery", "Manna preparation", "V-shape body position"],
    commonMistakes: ["Relying on shoulder elevation", "Not enough compression", "Toes not pointed", "Bent knees"],
    prerequisites: ["l_sit"],
    progressions: ["manna"],
    regressions: ["l_sit"],
    relatedSkills: ["manna"],
    masteryCategories: ["strength", "static_strength", "mobility"],
    coachingTips: ["Hip flexor strength is key", "Compression flexibility required", "Start at 45 degrees"],
    isLegendary: false,
    tags: ["intermediate", "core", "compression"],
  },
  {
    id: "shrimp_squat",
    name: "Shrimp Squat",
    icon: "🦐",
    tier: "intermediate",
    domain: "legs",
    description: "Single-leg squat with rear foot held behind.",
    purpose: "Develops quad strength and hip flexor flexibility.",
    benefits: ["Quad isolation", "Hip flexor flexibility", "Balance training", "Dragon squat preparation"],
    commonMistakes: ["Knee touching floor", "Insufficient depth", "Forward lean", "Neglecting hip flexor stretch"],
    prerequisites: ["pistol_squat"],
    progressions: ["dragon_squat"],
    regressions: ["pistol_squat"],
    relatedSkills: ["dragon_squat", "pistol_squat"],
    masteryCategories: ["strength", "mobility"],
    coachingTips: ["Upright torso", "Full knee bend", "Develop hip flexor flexibility"],
    isLegendary: false,
    tags: ["intermediate", "legs", "quad"],
  },

  // ─── ADVANCED ─────────────────────────────────────────────────────────────────
  {
    id: "one_arm_push_up",
    name: "One Arm Push-Up",
    icon: "✊",
    tier: "advanced",
    domain: "push",
    description: "Full range push-up on a single arm.",
    purpose: "Pinnacle of push-up strength and balance.",
    benefits: ["Ultimate push strength", "Unilateral balance", "Core anti-rotation", "Impressive skill"],
    commonMistakes: ["Hip rotation", "Foot placement too wide", "Partial range", "Rushing from archer"],
    prerequisites: ["archer_push_up"],
    progressions: [],
    regressions: ["archer_push_up"],
    relatedSkills: ["archer_push_up"],
    masteryCategories: ["strength", "balance"],
    coachingTips: ["Archer push-ups first", "Core alignment essential", "Feet shoulder width apart"],
    isLegendary: false,
    tags: ["advanced", "push", "unilateral"],
  },
  {
    id: "handstand_push_up",
    name: "Handstand Push-Up",
    icon: "🔽",
    tier: "advanced",
    domain: "push",
    description: "Full range push-up in a handstand position.",
    purpose: "Develops overhead pushing strength in inversion.",
    benefits: ["Overhead strength", "Shoulder mass", "Inversion strength", "Gymnastic foundation"],
    commonMistakes: ["Wall-supported indefinitely", "Insufficient range", "Arched back", "Head position wrong"],
    prerequisites: ["freestanding_handstand"],
    progressions: ["press_handstand"],
    regressions: ["wall_handstand"],
    relatedSkills: ["press_handstand", "one_arm_handstand"],
    journeyId: "handstand",
    masteryCategories: ["strength", "balance"],
    coachingTips: ["Wall-supported first", "Forehead to floor range", "Head through at bottom"],
    isLegendary: false,
    tags: ["advanced", "push", "handstand"],
  },
  {
    id: "dragon_flag",
    name: "Dragon Flag",
    icon: "🐉",
    tier: "advanced",
    domain: "core",
    description: "Full body leverage exercise on a bench.",
    purpose: "Builds complete core strength from a lever position.",
    benefits: ["Total core development", "Lever strength", "Athletic power", "Impressive skill"],
    commonMistakes: ["Touching ground", "Not holding at bottom", "Hips dropping", "Insufficient base"],
    prerequisites: ["hollow_body", "l_sit"],
    progressions: [],
    regressions: ["hollow_body"],
    relatedSkills: ["l_sit", "front_lever"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Negative reps first", "Keep body rigid", "Head rests on bench"],
    isLegendary: false,
    tags: ["advanced", "core", "lever"],
  },
  {
    id: "adv_tuck_front_lever",
    name: "Advanced Tuck Front Lever",
    icon: "🎯",
    tier: "advanced",
    domain: "pull",
    description: "Front lever with hips slightly open.",
    purpose: "Bridges tuck and straddle front lever.",
    benefits: ["Progressive loading", "Lat strength", "Technique refinement", "Consistency building"],
    commonMistakes: ["Hips too high", "Not straight arms", "Insufficient hold time", "Skipping to straddle"],
    prerequisites: ["tuck_front_lever"],
    progressions: ["straddle_front_lever"],
    regressions: ["tuck_front_lever"],
    relatedSkills: ["straddle_front_lever", "full_front_lever"],
    journeyId: "front_lever",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Hips open 45 degrees", "Straight arms always", "Build to 5 second holds"],
    isLegendary: false,
    tags: ["advanced", "pull", "front-lever"],
  },
  {
    id: "straddle_front_lever",
    name: "Straddle Front Lever",
    icon: "🎯",
    tier: "advanced",
    domain: "pull",
    description: "Front lever with legs in straddle position.",
    purpose: "Second-to-last step in the front lever progression.",
    benefits: ["Near-full lever strength", "Lat mastery", "Endurance building", "Full lever preparation"],
    commonMistakes: ["Legs not parallel to ground", "Bent arms", "Insufficient hold time", "Not opening legs enough"],
    prerequisites: ["adv_tuck_front_lever"],
    progressions: ["full_front_lever"],
    regressions: ["adv_tuck_front_lever"],
    relatedSkills: ["full_front_lever"],
    journeyId: "front_lever",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Wider straddle is easier", "Horizontal is the goal", "Daily practice essential"],
    isLegendary: false,
    tags: ["advanced", "pull", "front-lever"],
  },
  {
    id: "adv_tuck_planche",
    name: "Advanced Tuck Planche",
    icon: "👐",
    tier: "advanced",
    domain: "static",
    description: "Tuck planche with hips slightly open.",
    purpose: "Bridges tuck and straddle planche.",
    benefits: ["Progressive planche loading", "Wrist conditioning", "Shoulder strength", "Technique development"],
    commonMistakes: ["Hips too high", "Bent elbows", "Insufficient forward lean", "Ignoring wrist prep"],
    prerequisites: ["tuck_planche"],
    progressions: ["straddle_planche"],
    regressions: ["tuck_planche"],
    relatedSkills: ["straddle_planche", "full_planche"],
    journeyId: "planche",
    masteryCategories: ["strength", "static_strength", "balance"],
    coachingTips: ["Open hips gradually", "Shoulders over hands", "Max 3 second holds initially"],
    isLegendary: false,
    tags: ["advanced", "static", "planche"],
  },
  {
    id: "tuck_human_flag",
    name: "Tuck Human Flag",
    icon: "🚩",
    tier: "advanced",
    domain: "static",
    description: "Human flag with legs tucked.",
    purpose: "First horizontal hold in the human flag progression.",
    benefits: ["Lateral strength", "Horizontal hold practice", "Full flag preparation", "Shoulder conditioning"],
    commonMistakes: ["Hips sagging", "Arms bent", "Wrong pole grip", "Insufficient push-pull ratio"],
    prerequisites: ["vertical_flag"],
    progressions: ["extended_human_flag"],
    regressions: ["vertical_flag"],
    relatedSkills: ["full_human_flag"],
    journeyId: "human_flag",
    masteryCategories: ["strength", "static_strength", "balance"],
    coachingTips: ["Push with bottom arm hard", "Pull with top arm", "Keep body as horizontal as possible"],
    isLegendary: false,
    tags: ["advanced", "static", "human-flag"],
  },
  {
    id: "press_handstand",
    name: "Press Handstand",
    icon: "⬆️",
    tier: "advanced",
    domain: "balance",
    description: "Press from L-sit or straddle to handstand.",
    purpose: "Combines compression, shoulder and pressing strength.",
    benefits: ["Compression + pressing strength", "Handstand control", "Unique skill combination", "Flow state movement"],
    commonMistakes: ["Insufficient compression", "Jumping into press", "Wrong body position", "Skipping L-sit"],
    prerequisites: ["freestanding_handstand", "l_sit"],
    progressions: ["one_arm_handstand"],
    regressions: ["handstand_push_up"],
    relatedSkills: ["one_arm_handstand"],
    masteryCategories: ["balance", "strength", "static_strength"],
    coachingTips: ["Compression strength is key", "Straddle press easier first", "Control the descent"],
    isLegendary: false,
    tags: ["advanced", "balance", "handstand"],
  },
  {
    id: "ring_muscle_up",
    name: "Ring Muscle-Up",
    icon: "💍",
    tier: "advanced",
    domain: "pull",
    description: "Muscle-up performed on gymnastic rings.",
    purpose: "Develops ring-specific strength and stability.",
    benefits: ["Ring stability", "Higher skill ceiling", "Shoulder stability", "Foundation for ring skills"],
    commonMistakes: ["Ring instability ignored", "Wrong false grip", "Not completing dip portion", "Bar muscle-up dependency"],
    prerequisites: ["muscle_up"],
    progressions: [],
    regressions: ["muscle_up"],
    relatedSkills: ["iron_cross"],
    masteryCategories: ["strength", "explosiveness", "balance"],
    coachingTips: ["False grip is essential", "Rings turn out at top", "Start with kipping"],
    isLegendary: false,
    tags: ["advanced", "pull", "rings"],
  },
  {
    id: "archer_pull_up",
    name: "Archer Pull-Up",
    icon: "🎋",
    tier: "advanced",
    domain: "pull",
    description: "Unilateral pull-up with extended arm.",
    purpose: "Bridges the gap to the one-arm pull-up.",
    benefits: ["Unilateral pulling strength", "OAP preparation", "Lat isolation", "Grip strength"],
    commonMistakes: ["Rotating the torso", "Extended arm not straight", "Insufficient pull strength base", "Skipping from regular pull-up"],
    prerequisites: ["pull_up"],
    progressions: ["one_arm_pull_up"],
    regressions: ["pull_up"],
    relatedSkills: ["one_arm_pull_up"],
    masteryCategories: ["strength", "grip"],
    coachingTips: ["Full retraction at top", "Control the negative", "15+ pull-up base needed"],
    isLegendary: false,
    tags: ["advanced", "pull", "unilateral"],
  },
  {
    id: "extended_human_flag",
    name: "Extended Human Flag",
    icon: "🚩",
    tier: "advanced",
    domain: "static",
    description: "Human flag with legs partially extended.",
    purpose: "Progresses from tuck toward full human flag.",
    benefits: ["Increasing leverage", "Lateral strength development", "Flag preparation", "Endurance building"],
    commonMistakes: ["Extending too fast", "Body not horizontal", "Insufficient hold time", "Gripping too high"],
    prerequisites: ["tuck_human_flag"],
    progressions: ["full_human_flag"],
    regressions: ["tuck_human_flag"],
    relatedSkills: ["full_human_flag"],
    journeyId: "human_flag",
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Increase extension gradually", "Body must be horizontal", "Build to 3 second holds"],
    isLegendary: false,
    tags: ["advanced", "static", "human-flag"],
  },

  // ─── ELITE ────────────────────────────────────────────────────────────────────
  {
    id: "front_lever",
    name: "Front Lever",
    icon: "🎯",
    tier: "elite",
    domain: "static",
    description: "Full horizontal hold with body parallel to ground on bar.",
    purpose: "Demonstrates elite lat and core strength in a lever position.",
    benefits: ["Develops exceptional lat strength", "Builds shoulder stability", "Foundation for iron cross", "Supreme pulling power"],
    commonMistakes: ["Insufficient scapular depression", "Bent arms", "Rushing progressions", "Neglecting hip flexor strength"],
    prerequisites: ["straddle_front_lever"],
    progressions: ["full_front_lever"],
    regressions: ["straddle_front_lever"],
    relatedSkills: ["full_front_lever", "iron_cross"],
    journeyId: "front_lever",
    masteryCategories: ["strength", "static_strength", "grip"],
    coachingTips: ["Tuck progression first", "Straight body line", "Depression and retraction"],
    isLegendary: true,
    tags: ["elite", "pull", "front-lever", "legendary"],
  },
  {
    id: "human_flag",
    name: "Human Flag",
    icon: "🚩",
    tier: "elite",
    domain: "static",
    description: "Horizontal hold on a vertical pole.",
    purpose: "Develops extreme lateral body strength and control.",
    benefits: ["Lateral strength mastery", "Unique movement pattern", "Extreme core control", "Visual impact"],
    commonMistakes: ["Insufficient push-pull ratio", "Wrong pole grip", "Body not horizontal", "Too little base strength"],
    prerequisites: ["extended_human_flag"],
    progressions: ["full_human_flag"],
    regressions: ["extended_human_flag"],
    relatedSkills: ["full_human_flag"],
    journeyId: "human_flag",
    masteryCategories: ["strength", "balance", "static_strength"],
    coachingTips: ["Lateral strength is unique", "Straddle position easier", "Shoulder press strength needed"],
    isLegendary: true,
    tags: ["elite", "static", "human-flag", "legendary"],
  },
  {
    id: "tuck_planche",
    name: "Tuck Planche",
    icon: "🔄",
    tier: "elite",
    domain: "static",
    description: "Hold a planche with legs tucked to chest.",
    purpose: "First true planche hold.",
    benefits: ["First full planche hold", "Shoulder strength", "Wrist conditioning", "Foundation for full planche"],
    commonMistakes: ["Hips too high", "Bent elbows", "Insufficient forward lean", "Wrist not conditioned"],
    prerequisites: ["adv_tuck_planche"],
    progressions: ["adv_tuck_planche", "straddle_planche"],
    regressions: ["pseudo_planche_push_up"],
    relatedSkills: ["straddle_planche", "full_planche"],
    journeyId: "planche",
    masteryCategories: ["strength", "static_strength", "balance"],
    coachingTips: ["Shoulders must be fully depressed", "Wrist conditioning key", "Head slightly forward"],
    isLegendary: true,
    tags: ["elite", "static", "planche", "legendary"],
  },
  {
    id: "one_arm_pull_up",
    name: "One Arm Pull-Up",
    icon: "💎",
    tier: "elite",
    domain: "pull",
    description: "Pull-up performed on a single arm.",
    purpose: "The ultimate test of relative pulling strength.",
    benefits: ["Ultimate pulling strength", "Unilateral lat power", "Tendon conditioning", "Rare elite skill"],
    commonMistakes: ["Insufficient base (need 25+ pull-ups)", "Wrist not conditioned", "Rotating at hip", "Progressing too fast"],
    prerequisites: ["archer_pull_up"],
    progressions: [],
    regressions: ["archer_pull_up"],
    relatedSkills: ["archer_pull_up", "front_lever"],
    journeyId: "one_arm_pullup",
    masteryCategories: ["strength", "grip", "static_strength"],
    coachingTips: ["Archer pull-ups bridge", "Wrist needs to be strong", "Gradual loading essential"],
    isLegendary: true,
    tags: ["elite", "pull", "unilateral", "legendary"],
  },
  {
    id: "back_lever",
    name: "Back Lever",
    icon: "🔙",
    tier: "elite",
    domain: "static",
    description: "Horizontal hold facing down on a bar or rings.",
    purpose: "Develops posterior chain strength and shoulder flexibility.",
    benefits: ["Shoulder flexibility", "Posterior chain strength", "Foundation for more advanced levers", "Unique body control"],
    commonMistakes: ["Insufficient shoulder flexibility", "Bent arms", "Not horizontal", "Skipping skin the cat work"],
    prerequisites: ["pull_up", "l_sit"],
    progressions: [],
    regressions: ["tuck_front_lever"],
    relatedSkills: ["front_lever"],
    masteryCategories: ["strength", "static_strength", "mobility"],
    coachingTips: ["Skin the cat first", "Tuck then extend", "Shoulder stretch essential"],
    isLegendary: true,
    tags: ["elite", "static", "lever", "legendary"],
  },
  {
    id: "straddle_planche",
    name: "Straddle Planche",
    icon: "👐",
    tier: "elite",
    domain: "static",
    description: "Planche with legs in straddle position.",
    purpose: "Second-to-last step in the planche progression.",
    benefits: ["Near-full planche strength", "Shoulder mastery", "Wrist conditioning complete", "Full planche preparation"],
    commonMistakes: ["Not fully horizontal", "Legs not in straddle", "Insufficient hold time", "Bent elbows"],
    prerequisites: ["adv_tuck_planche"],
    progressions: ["full_planche"],
    regressions: ["adv_tuck_planche"],
    relatedSkills: ["full_planche"],
    journeyId: "planche",
    masteryCategories: ["strength", "static_strength", "balance"],
    coachingTips: ["Wider straddle is easier", "Body must be horizontal", "Daily practice"],
    isLegendary: true,
    tags: ["elite", "static", "planche", "legendary"],
  },

  // ─── LEGENDARY ────────────────────────────────────────────────────────────────
  {
    id: "full_front_lever",
    name: "Full Front Lever",
    icon: "🌟",
    tier: "legendary",
    domain: "static",
    description: "Horizontal hold with body fully parallel to ground, legs together.",
    purpose: "The pinnacle of pulling leverage strength.",
    benefits: ["Pinnacle of lat strength", "Complete posterior chain mastery", "Foundation for Olympic gymnastics", "Extreme pulling power"],
    commonMistakes: ["Legs not together", "Body not horizontal", "Bent arms at any point", "Rushing from straddle"],
    prerequisites: ["front_lever", "straddle_front_lever"],
    progressions: [],
    regressions: ["straddle_front_lever"],
    relatedSkills: ["iron_cross"],
    journeyId: "front_lever",
    masteryCategories: ["strength", "static_strength", "grip"],
    coachingTips: ["Straight body is the goal", "Back strength is paramount", "Years of training required"],
    isLegendary: true,
    tags: ["legendary", "pull", "front-lever"],
  },
  {
    id: "full_planche",
    name: "Full Planche",
    icon: "👐",
    tier: "legendary",
    domain: "static",
    description: "Hold a planche with body fully horizontal, legs together.",
    purpose: "The pinnacle of straight-arm pushing strength.",
    benefits: ["Pinnacle of pushing strength", "Complete wrist conditioning", "Gymnastic elite status", "Extreme shoulder power"],
    commonMistakes: ["Legs not fully together", "Not completely horizontal", "Bent elbows", "Insufficient planche lean time"],
    prerequisites: ["straddle_planche"],
    progressions: [],
    regressions: ["straddle_planche"],
    relatedSkills: ["iron_cross"],
    journeyId: "planche",
    masteryCategories: ["strength", "static_strength", "balance"],
    coachingTips: ["Years of dedicated training", "Maximize wrist conditioning", "Straight arm strength"],
    isLegendary: true,
    tags: ["legendary", "push", "planche"],
  },
  {
    id: "iron_cross",
    name: "Iron Cross",
    icon: "✝️",
    tier: "legendary",
    domain: "static",
    description: "Hold body at 90° on rings with arms extended.",
    purpose: "Demonstrates the ultimate in ring strength.",
    benefits: ["Ultimate ring strength", "Extreme shoulder integrity", "Exceptional static power", "Pinnacle of gymnastics strength"],
    commonMistakes: ["Insufficient straight-arm strength base", "Skipping ring rows", "Progressing too fast", "Neglecting bicep tendon conditioning"],
    prerequisites: ["one_arm_pull_up", "ring_muscle_up"],
    progressions: [],
    regressions: ["ring_muscle_up"],
    relatedSkills: ["full_front_lever", "victorian"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Ring strength is unique", "Years of ring training required", "Straight arm conditioning from day 1"],
    isLegendary: true,
    tags: ["legendary", "rings", "static"],
  },
  {
    id: "full_human_flag",
    name: "Full Human Flag",
    icon: "🚩",
    tier: "legendary",
    domain: "static",
    description: "Complete horizontal human flag with straight legs.",
    purpose: "The ultimate lateral strength expression.",
    benefits: ["Ultimate lateral strength", "Extreme core control", "Rare elite skill", "Athletic pinnacle"],
    commonMistakes: ["Legs not fully straight", "Not horizontal", "Insufficient base training", "Wrong pole technique"],
    prerequisites: ["human_flag", "extended_human_flag"],
    progressions: [],
    regressions: ["human_flag"],
    relatedSkills: ["iron_cross"],
    journeyId: "human_flag",
    masteryCategories: ["strength", "balance", "static_strength"],
    coachingTips: ["Straight body throughout", "Push arm straight", "Pull arm straight", "Hip drive for balance"],
    isLegendary: true,
    tags: ["legendary", "static", "human-flag"],
  },
  {
    id: "one_arm_handstand",
    name: "One Arm Handstand",
    icon: "🌟",
    tier: "legendary",
    domain: "balance",
    description: "Hold a freestanding handstand on a single arm.",
    purpose: "Peak of balance and unilateral shoulder strength.",
    benefits: ["Peak balance mastery", "Unilateral shoulder strength", "Elite proprioception", "Pinnacle of handstand work"],
    commonMistakes: ["Insufficient two-arm handstand time", "Lateral drift", "Bent elbow", "Too little wrist conditioning"],
    prerequisites: ["freestanding_handstand", "press_handstand"],
    progressions: [],
    regressions: ["press_handstand"],
    relatedSkills: ["press_handstand"],
    masteryCategories: ["balance", "strength", "coordination"],
    coachingTips: ["Needs 60+ second two-arm first", "Wall support gradually removed", "Finger spreading critical"],
    isLegendary: true,
    tags: ["legendary", "balance", "handstand"],
  },
  {
    id: "manna",
    name: "Manna",
    icon: "🙏",
    tier: "legendary",
    domain: "static",
    description: "Hands behind hips, body elevated horizontal.",
    purpose: "Extreme shoulder flexibility and hip flexor strength.",
    benefits: ["Extreme shoulder flexibility", "Unique lever strength", "Elite hip flexor power", "Gymnastic foundation skill"],
    commonMistakes: ["Insufficient hip flexor flexibility", "Insufficient shoulder extension", "Rushing from V-sit", "Neglecting wrist conditioning"],
    prerequisites: ["v_sit"],
    progressions: [],
    regressions: ["v_sit"],
    relatedSkills: ["v_sit", "iron_cross"],
    masteryCategories: ["strength", "static_strength", "mobility"],
    coachingTips: ["Shoulder extension flexibility critical", "Hip flexor work daily", "V-sit must be solid"],
    isLegendary: true,
    tags: ["legendary", "core", "static"],
  },
  {
    id: "victorian",
    name: "Victorian Cross",
    icon: "👑",
    tier: "legendary",
    domain: "static",
    description: "Inverted iron cross — body above rings, arms extended.",
    purpose: "Pinnacle of ring and bicep strength.",
    benefits: ["Pinnacle of ring strength", "Extreme bicep power", "Elite straight-arm strength", "Rarest gymnastics hold"],
    commonMistakes: ["Insufficient iron cross base", "Elbow hyperextension risk", "No proper tendon conditioning", "Skipping prerequisites"],
    prerequisites: ["iron_cross"],
    progressions: [],
    regressions: ["iron_cross"],
    relatedSkills: ["iron_cross", "maltese"],
    masteryCategories: ["strength", "static_strength"],
    coachingTips: ["Iron cross must be solid first", "Bicep tendon conditioning crucial", "Years of ring work"],
    isLegendary: true,
    tags: ["legendary", "rings", "static"],
  },
  {
    id: "maltese",
    name: "Maltese",
    icon: "✚",
    tier: "legendary",
    domain: "static",
    description: "Wide iron cross position at hip level on rings.",
    purpose: "Ultimate ring strength requiring wide lever position.",
    benefits: ["Ultimate lever strength", "Wide shoulder power", "Rarest calisthenics skill", "Olympic gymnastics level"],
    commonMistakes: ["No iron cross first", "Rings at wrong height", "Insufficient shoulder strength", "No gradual loading"],
    prerequisites: ["iron_cross", "full_planche"],
    progressions: [],
    regressions: ["iron_cross"],
    relatedSkills: ["victorian", "iron_cross"],
    masteryCategories: ["strength", "static_strength", "balance"],
    coachingTips: ["Iron cross and planche both required", "Extremely long progression", "Professional coaching recommended"],
    isLegendary: true,
    tags: ["legendary", "rings", "static"],
  },
  {
    id: "ninety_degree_push_up",
    name: "90 Degree Push-Up",
    icon: "🔢",
    tier: "legendary",
    domain: "push",
    description: "Push-up from planche to L-sit position.",
    purpose: "Combines planche and compression strength in one movement.",
    benefits: ["Combined planche + L-sit strength", "Dynamic lever strength", "Elite skill combination", "Gymnastics pinnacle"],
    commonMistakes: ["No planche base", "No L-sit base", "Insufficient wrist conditioning", "Rushing transition"],
    prerequisites: ["full_planche", "l_sit"],
    progressions: [],
    regressions: ["full_planche"],
    relatedSkills: ["full_planche", "manna"],
    masteryCategories: ["strength", "static_strength", "explosiveness"],
    coachingTips: ["Both planche and L-sit must be solid", "Transition requires practice", "Elite level commitment"],
    isLegendary: true,
    tags: ["legendary", "push", "planche"],
  },

  // ─── ADDITIONAL CHAIN SKILLS ──────────────────────────────────────────────────
  {
    id: "dragon_squat",
    name: "Dragon Squat",
    icon: "🐲",
    tier: "advanced",
    domain: "legs",
    description: "Extreme single-leg squat with rear leg crossing under.",
    purpose: "Ultimate single-leg strength and hip mobility challenge.",
    benefits: ["Extreme hip mobility", "Unilateral strength", "Impressive skill", "Complete leg mastery"],
    commonMistakes: ["Insufficient hip flexibility", "Knee collapsing", "Not controlling descent", "Ignoring mobility work"],
    prerequisites: ["shrimp_squat"],
    progressions: [],
    regressions: ["shrimp_squat"],
    relatedSkills: ["shrimp_squat", "pistol_squat"],
    masteryCategories: ["strength", "mobility"],
    coachingTips: ["Hip flexor flexibility essential", "Shrimp squat must be solid", "Start with assisted version"],
    isLegendary: false,
    tags: ["advanced", "legs", "mobility"],
  },
];

export const SKILL_LIBRARY_MAP: Record<string, LibrarySkill> = Object.fromEntries(
  LIBRARY_SKILLS.map((s) => [s.id, s])
);
