import { MovementStandard } from "./movement-standards-types";

export const MOVEMENT_STANDARDS: MovementStandard[] = [

  // ── STRENGTH ──────────────────────────────────────────────────────────────
  {
    id: "pull_ups",
    name: "Pull-Ups",
    icon: "🔼",
    category: "strength",
    measureType: "reps",
    unit: "reps",
    description: "Maximum strict pull-ups in one set.",
    recordKey: "pull_ups",
    relatedSkillId: "pull_up",
    relatedJourneyId: "front_lever",
    featured: true,
    thresholds: [
      { rank: "bronze",    value: 5,  label: "5 reps",   description: "Foundational pulling strength" },
      { rank: "silver",    value: 10, label: "10 reps",  description: "Solid pulling base" },
      { rank: "gold",      value: 15, label: "15 reps",  description: "Strong pulling ability" },
      { rank: "elite",     value: 20, label: "20 reps",  description: "Elite pulling strength" },
      { rank: "legendary", value: 30, label: "30 reps",  description: "Exceptional endurance + strength" },
    ],
    tips: ["Dead hang each rep", "Full ROM chin over bar", "Control the negative"],
  },
  {
    id: "push_ups",
    name: "Push-Ups",
    icon: "💪",
    category: "strength",
    measureType: "reps",
    unit: "reps",
    description: "Maximum strict push-ups in one set.",
    recordKey: "push_ups",
    relatedSkillId: "push_up",
    featured: true,
    thresholds: [
      { rank: "bronze",    value: 20,  label: "20 reps",  description: "Basic push strength" },
      { rank: "silver",    value: 40,  label: "40 reps",  description: "Good muscular endurance" },
      { rank: "gold",      value: 60,  label: "60 reps",  description: "Strong upper body endurance" },
      { rank: "elite",     value: 80,  label: "80 reps",  description: "Elite pushing endurance" },
      { rank: "legendary", value: 100, label: "100 reps", description: "Extraordinary endurance" },
    ],
    tips: ["Chest to floor each rep", "Elbows 45°", "Core tight throughout"],
  },
  {
    id: "dips",
    name: "Dips",
    icon: "⬇️",
    category: "strength",
    measureType: "reps",
    unit: "reps",
    description: "Maximum strict parallel bar dips.",
    recordKey: "dips",
    thresholds: [
      { rank: "bronze",    value: 5,  label: "5 reps",  description: "Basic dip strength" },
      { rank: "silver",    value: 10, label: "10 reps", description: "Solid dip base" },
      { rank: "gold",      value: 15, label: "15 reps", description: "Good dip strength" },
      { rank: "elite",     value: 20, label: "20 reps", description: "Elite dip strength" },
      { rank: "legendary", value: 30, label: "30 reps", description: "Extraordinary dip endurance" },
    ],
    tips: ["Full ROM — shoulders below elbows", "Upright torso for tricep focus", "Control descent"],
  },
  {
    id: "pistol_squats",
    name: "Pistol Squats",
    icon: "🦵",
    category: "strength",
    measureType: "reps",
    unit: "reps",
    description: "Maximum pistol squats per leg.",
    recordKey: "pistol_squats",
    relatedSkillId: "pistol_squat",
    thresholds: [
      { rank: "bronze",    value: 3,  label: "3 reps",  description: "Can perform the movement" },
      { rank: "silver",    value: 5,  label: "5 reps",  description: "Consistent single-leg strength" },
      { rank: "gold",      value: 10, label: "10 reps", description: "Strong single-leg ability" },
      { rank: "elite",     value: 15, label: "15 reps", description: "Elite single-leg strength" },
      { rank: "legendary", value: 20, label: "20 reps", description: "Extraordinary leg mastery" },
    ],
    tips: ["Heel flat", "Control descent to parallel", "Keep non-working leg extended"],
  },
  {
    id: "muscle_ups",
    name: "Muscle-Ups",
    icon: "🔝",
    category: "power",
    measureType: "reps",
    unit: "reps",
    description: "Maximum bar or ring muscle-ups.",
    recordKey: "muscle_ups",
    relatedSkillId: "muscle_up",
    relatedJourneyId: "muscle_up",
    featured: true,
    thresholds: [
      { rank: "bronze",    value: 1,  label: "1 rep",   description: "First muscle-up achieved" },
      { rank: "silver",    value: 3,  label: "3 reps",  description: "Consistent muscle-ups" },
      { rank: "gold",      value: 5,  label: "5 reps",  description: "Strong muscle-up ability" },
      { rank: "elite",     value: 10, label: "10 reps", description: "Elite muscle-up power" },
      { rank: "legendary", value: 15, label: "15 reps", description: "Extraordinary power endurance" },
    ],
    tips: ["Explosive pull phase", "Lean forward at transition", "Straight bar is harder than rings"],
  },

  // ── GRIP / STATIC ────────────────────────────────────────────────────────
  {
    id: "dead_hang",
    name: "Dead Hang",
    icon: "🧱",
    category: "grip",
    measureType: "seconds",
    unit: "seconds",
    description: "Maximum dead hang time.",
    recordKey: "dead_hang",
    relatedSkillId: "dead_hang",
    featured: true,
    thresholds: [
      { rank: "bronze",    value: 30,  label: "30s",  description: "Basic grip endurance" },
      { rank: "silver",    value: 60,  label: "60s",  description: "Solid grip base" },
      { rank: "gold",      value: 90,  label: "90s",  description: "Strong grip endurance" },
      { rank: "elite",     value: 120, label: "120s", description: "Elite grip strength" },
      { rank: "legendary", value: 180, label: "180s", description: "Extraordinary grip mastery" },
    ],
    tips: ["Full grip — all fingers", "Relax shoulders into hang", "Breathe steadily"],
  },
  {
    id: "l_sit",
    name: "L-Sit",
    icon: "📐",
    category: "static_strength",
    measureType: "seconds",
    unit: "seconds",
    description: "L-sit hold time on parallettes or floor.",
    recordKey: "l_sit",
    relatedSkillId: "l_sit",
    relatedJourneyId: "l_sit",
    featured: true,
    thresholds: [
      { rank: "bronze",    value: 10, label: "10s", description: "Basic L-sit hold" },
      { rank: "silver",    value: 20, label: "20s", description: "Developing compression" },
      { rank: "gold",      value: 30, label: "30s", description: "Strong isometric hold" },
      { rank: "elite",     value: 45, label: "45s", description: "Elite compression strength" },
      { rank: "legendary", value: 60, label: "60s", description: "L-sit mastery" },
    ],
    tips: ["Point toes", "Depress scapulae", "Straight legs throughout"],
  },
  {
    id: "planche_hold",
    name: "Planche Hold",
    icon: "👐",
    category: "static_strength",
    measureType: "qualitative",
    unit: "level",
    description: "Highest planche progression held for 3+ seconds.",
    relatedSkillId: "tuck_planche",
    relatedJourneyId: "planche",
    featured: true,
    qualitativeLabels: [
      "Planche Lean", "Tuck Planche", "Advanced Tuck", "Straddle Planche", "Full Planche"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "Planche Lean",     description: "Leaning forward on straight arms" },
      { rank: "silver",    value: 1, label: "Tuck Planche",     description: "Hold with legs tucked to chest" },
      { rank: "gold",      value: 2, label: "Advanced Tuck",    description: "Back parallel, knees to chest" },
      { rank: "elite",     value: 3, label: "Straddle Planche", description: "Full body elevated, legs straddled" },
      { rank: "legendary", value: 4, label: "Full Planche",     description: "Body fully horizontal, legs together" },
    ],
    tips: ["Wrist prep daily", "Shoulder depression is key", "Straight arms from the start"],
  },
  {
    id: "front_lever_hold",
    name: "Front Lever",
    icon: "🎯",
    category: "static_strength",
    measureType: "qualitative",
    unit: "level",
    description: "Highest front lever progression held for 3+ seconds.",
    relatedSkillId: "front_lever",
    relatedJourneyId: "front_lever",
    featured: true,
    qualitativeLabels: [
      "Tuck Front Lever", "Advanced Tuck", "Straddle Front Lever", "Full Front Lever", "Full FL 20s+"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "Tuck Front Lever",     description: "Knees tucked to chest" },
      { rank: "silver",    value: 1, label: "Advanced Tuck",        description: "Back parallel, knees out" },
      { rank: "gold",      value: 2, label: "Straddle Front Lever", description: "Legs straddled, body horizontal" },
      { rank: "elite",     value: 3, label: "Full Front Lever",     description: "Legs together, fully horizontal" },
      { rank: "legendary", value: 4, label: "Full FL 20s+",         description: "Full front lever for 20+ seconds" },
    ],
    tips: ["Scapular depression and retraction", "Keep arms straight", "Progression order matters"],
  },

  // ── BALANCE ──────────────────────────────────────────────────────────────
  {
    id: "handstand_hold",
    name: "Handstand Hold",
    icon: "🤸",
    category: "balance",
    measureType: "qualitative",
    unit: "level",
    description: "Best handstand hold progression.",
    relatedSkillId: "handstand",
    relatedJourneyId: "handstand",
    featured: true,
    qualitativeLabels: [
      "10s Wall Hold", "30s Wall Hold", "10s Freestanding", "30s Freestanding", "60s+ Freestanding"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "10s Wall Hold",     description: "Basic wall support" },
      { rank: "silver",    value: 1, label: "30s Wall Hold",     description: "Solid wall hold" },
      { rank: "gold",      value: 2, label: "10s Freestanding",  description: "First freestanding holds" },
      { rank: "elite",     value: 3, label: "30s Freestanding",  description: "Consistent freestanding" },
      { rank: "legendary", value: 4, label: "60s+ Freestanding", description: "Handstand mastery" },
    ],
    tips: ["Fingers spread wide", "Squeeze glutes", "Line: wrist → shoulder → hip → heel"],
  },
  {
    id: "human_flag_hold",
    name: "Human Flag",
    icon: "🚩",
    category: "balance",
    measureType: "qualitative",
    unit: "level",
    description: "Best human flag progression held.",
    relatedSkillId: "human_flag",
    relatedJourneyId: "human_flag",
    featured: true,
    qualitativeLabels: [
      "Vertical Flag", "Tuck Human Flag", "Extended Flag", "Full Human Flag", "Full Flag 5s+"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "Vertical Flag",   description: "Body vertical on the pole" },
      { rank: "silver",    value: 1, label: "Tuck Human Flag", description: "Horizontal with legs tucked" },
      { rank: "gold",      value: 2, label: "Extended Flag",   description: "One leg extended horizontal" },
      { rank: "elite",     value: 3, label: "Full Human Flag", description: "Full horizontal flag" },
      { rank: "legendary", value: 4, label: "Full Flag 5s+",   description: "Full flag held for 5+ seconds" },
    ],
    tips: ["Lat strength critical", "Push bottom arm, pull top arm", "Lateral strength is unique"],
  },

  // ── MOBILITY ──────────────────────────────────────────────────────────────
  {
    id: "pancake_stretch",
    name: "Pancake Stretch",
    icon: "🥞",
    category: "mobility",
    measureType: "qualitative",
    unit: "level",
    description: "Pancake (forward fold with legs straddled) depth.",
    qualitativeLabels: [
      "Hands to floor", "Forearms to floor", "Chest to floor", "Full flat", "Full + sustained 60s"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "Hands to floor",    description: "Fingertips touch floor" },
      { rank: "silver",    value: 1, label: "Forearms to floor", description: "Forearms flat on floor" },
      { rank: "gold",      value: 2, label: "Chest to floor",    description: "Chest touches floor" },
      { rank: "elite",     value: 3, label: "Fully flat",        description: "Completely flat fold" },
      { rank: "legendary", value: 4, label: "Sustained 60s",     description: "Full flat held 60 seconds" },
    ],
    tips: ["Daily active stretching", "Hip flexor work helps", "Patience — months of progress"],
  },
  {
    id: "bridge_hold",
    name: "Bridge Hold",
    icon: "🌉",
    category: "mobility",
    measureType: "qualitative",
    unit: "level",
    description: "Bridge quality and hold progression.",
    qualitativeLabels: [
      "Basic Bridge", "Full Bridge", "Bridge + Shoulder Extension", "Chest Bridge", "Pike Bridge"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "Basic Bridge",        description: "Basic back bridge hold" },
      { rank: "silver",    value: 1, label: "Full Bridge",         description: "Arms and legs straight" },
      { rank: "gold",      value: 2, label: "Shoulder Extension",  description: "Extended shoulder mobility" },
      { rank: "elite",     value: 3, label: "Chest Bridge",        description: "Chest to floor in bridge" },
      { rank: "legendary", value: 4, label: "Pike Bridge",         description: "Advanced bridge variations" },
    ],
    tips: ["Open chest daily", "Thoracic extension key", "Wrist warm-up essential"],
  },
  {
    id: "one_arm_hang",
    name: "One Arm Hang",
    icon: "🦾",
    category: "grip",
    measureType: "seconds",
    unit: "seconds",
    description: "Maximum one arm dead hang time.",
    recordKey: "one_arm_hang",
    thresholds: [
      { rank: "bronze",    value: 5,  label: "5s",  description: "First one arm hang" },
      { rank: "silver",    value: 10, label: "10s", description: "Developing one arm grip" },
      { rank: "gold",      value: 20, label: "20s", description: "Strong one arm hang" },
      { rank: "elite",     value: 30, label: "30s", description: "Elite one arm grip" },
      { rank: "legendary", value: 60, label: "60s", description: "Extraordinary grip mastery" },
    ],
    tips: ["Build two-arm hang first (90s+)", "Assisted progression", "Wrist strength critical"],
  },

  // ── POWER / EXPLOSIVENESS ──────────────────────────────────────────────
  {
    id: "clap_push_ups",
    name: "Clap Push-Ups",
    icon: "👏",
    category: "explosiveness",
    measureType: "reps",
    unit: "reps",
    description: "Maximum explosive clap push-ups.",
    recordKey: "clap_push_ups",
    thresholds: [
      { rank: "bronze",    value: 3,  label: "3 reps",  description: "Basic explosive push" },
      { rank: "silver",    value: 8,  label: "8 reps",  description: "Developing explosive power" },
      { rank: "gold",      value: 15, label: "15 reps", description: "Strong explosive ability" },
      { rank: "elite",     value: 20, label: "20 reps", description: "Elite explosive power" },
      { rank: "legendary", value: 30, label: "30 reps", description: "Extraordinary plyometric ability" },
    ],
    tips: ["Full push-up depth before explosion", "Hands shoulder-width", "Land softly"],
  },

  // ── ENDURANCE ────────────────────────────────────────────────────────────
  {
    id: "max_pull_up_hang",
    name: "Max Pull-Up Hang",
    icon: "⏱️",
    category: "endurance",
    measureType: "seconds",
    unit: "seconds",
    description: "Flexed arm hang time (chin over bar).",
    recordKey: "flexed_arm_hang",
    thresholds: [
      { rank: "bronze",    value: 15, label: "15s", description: "Basic flexed hang endurance" },
      { rank: "silver",    value: 30, label: "30s", description: "Solid pulling endurance" },
      { rank: "gold",      value: 45, label: "45s", description: "Strong pulling endurance" },
      { rank: "elite",     value: 60, label: "60s", description: "Elite pulling endurance" },
      { rank: "legendary", value: 90, label: "90s", description: "Extraordinary endurance" },
    ],
    tips: ["Consistent lat activation", "Neutral grip slightly easier", "Build grip base first"],
  },

  // ── COORDINATION ─────────────────────────────────────────────────────────
  {
    id: "free_handstand_walk",
    name: "Handstand Walk",
    icon: "🚶",
    category: "coordination",
    measureType: "reps",
    unit: "steps",
    description: "Maximum consecutive handstand walk steps.",
    recordKey: "handstand_walk",
    thresholds: [
      { rank: "bronze",    value: 3,   label: "3 steps",   description: "First handstand steps" },
      { rank: "silver",    value: 10,  label: "10 steps",  description: "Basic handstand walking" },
      { rank: "gold",      value: 20,  label: "20 steps",  description: "Solid handstand walk" },
      { rank: "elite",     value: 40,  label: "40 steps",  description: "Elite handstand movement" },
      { rank: "legendary", value: 100, label: "100 steps", description: "Handstand walk mastery" },
    ],
    tips: ["Master 30s+ freestanding first", "Small corrections with fingers", "Look slightly forward"],
  },

  // ── ADDITIONAL STANDARDS ─────────────────────────────────────────────────
  {
    id: "plank_hold",
    name: "Plank Hold",
    icon: "🪨",
    category: "static_strength",
    measureType: "seconds",
    unit: "seconds",
    description: "Maximum strict plank hold time.",
    recordKey: "plank",
    thresholds: [
      { rank: "bronze",    value: 60,  label: "60s",   description: "Basic core endurance" },
      { rank: "silver",    value: 120, label: "120s",  description: "Solid core base" },
      { rank: "gold",      value: 180, label: "180s",  description: "Strong core endurance" },
      { rank: "elite",     value: 300, label: "5 min", description: "Elite core strength" },
      { rank: "legendary", value: 600, label: "10 min",description: "Extraordinary core mastery" },
    ],
    tips: ["Neutral spine throughout", "Breathe steadily", "Squeeze glutes and abs together"],
  },
  {
    id: "hollow_body_hold",
    name: "Hollow Body Hold",
    icon: "🫙",
    category: "static_strength",
    measureType: "seconds",
    unit: "seconds",
    description: "Hollow body position hold time.",
    recordKey: "hollow_body",
    thresholds: [
      { rank: "bronze",    value: 20, label: "20s", description: "Basic hollow body" },
      { rank: "silver",    value: 40, label: "40s", description: "Developing the position" },
      { rank: "gold",      value: 60, label: "60s", description: "Solid hollow hold" },
      { rank: "elite",     value: 90, label: "90s", description: "Elite hollow body" },
      { rank: "legendary", value: 120,label: "120s",description: "Hollow body mastery" },
    ],
    tips: ["Lower back pressed to floor", "Arms overhead adds difficulty", "Breathe shallowly"],
  },
  {
    id: "dragon_flag",
    name: "Dragon Flag",
    icon: "🐉",
    category: "static_strength",
    measureType: "reps",
    unit: "reps",
    description: "Strict dragon flag repetitions.",
    thresholds: [
      { rank: "bronze",    value: 1,  label: "1 rep",  description: "First dragon flag" },
      { rank: "silver",    value: 3,  label: "3 reps", description: "Developing dragon flag" },
      { rank: "gold",      value: 5,  label: "5 reps", description: "Solid dragon flags" },
      { rank: "elite",     value: 8,  label: "8 reps", description: "Strong dragon flag ability" },
      { rank: "legendary", value: 12, label: "12 reps",description: "Dragon flag mastery" },
    ],
    tips: ["Shoulders only touch bench", "Keep body completely rigid", "Control eccentric fully"],
  },
  {
    id: "back_lever",
    name: "Back Lever",
    icon: "🔄",
    category: "static_strength",
    measureType: "qualitative",
    unit: "level",
    description: "Back lever progression holds.",
    qualitativeLabels: [
      "Skin the Cat", "Tuck Back Lever", "Advanced Tuck", "Straddle Back Lever", "Full Back Lever"
    ],
    thresholds: [
      { rank: "bronze",    value: 0, label: "Skin the Cat",      description: "Basic shoulder mobility" },
      { rank: "silver",    value: 1, label: "Tuck Back Lever",   description: "Hold with legs tucked" },
      { rank: "gold",      value: 2, label: "Advanced Tuck",     description: "Back parallel, knee extended" },
      { rank: "elite",     value: 3, label: "Straddle Back Lever",description: "Legs straddled horizontal" },
      { rank: "legendary", value: 4, label: "Full Back Lever",   description: "Full back lever hold" },
    ],
    tips: ["Shoulder prep essential", "Bicep tendon at risk — progress slowly", "Straight arms throughout"],
  },
  {
    id: "weighted_pull_ups",
    name: "Weighted Pull-Ups",
    icon: "⚖️",
    category: "strength",
    measureType: "reps",
    unit: "reps",
    description: "Pull-ups with bodyweight added (20kg+).",
    thresholds: [
      { rank: "bronze",    value: 1,  label: "1 rep",  description: "First weighted pull-up (10kg)" },
      { rank: "silver",    value: 3,  label: "3 reps", description: "Solid weighted pull-ups (15kg)" },
      { rank: "gold",      value: 5,  label: "5 reps", description: "Strong weighted pull-ups (20kg)" },
      { rank: "elite",     value: 8,  label: "8 reps", description: "Elite weighted pulling (25kg)" },
      { rank: "legendary", value: 5,  label: "5+ (40kg)", description: "Heavy weighted pull-up master" },
    ],
    tips: ["Build 20+ strict pull-ups first", "Use dip belt for best results", "Slow controlled reps"],
  },
];

export const STANDARDS_MAP: Record<string, MovementStandard> =
  Object.fromEntries(MOVEMENT_STANDARDS.map(s => [s.id, s]));

export const FEATURED_STANDARDS: MovementStandard[] =
  MOVEMENT_STANDARDS.filter(s => s.featured);
