import { SkillDef } from "./skill-requirements-types";

// ─── BEGINNER SKILLS ─────────────────────────────────────────────────────────

const BEGINNER_SKILLS: SkillDef[] = [
  {
    id: "push_up",
    name: "Push-Up",
    icon: "💪",
    tier: "beginner",
    domain: "push",
    description: "The foundation of all pushing movements.",
    requirements: [
      { type: "workout_count", target: "push", value: 1, label: "Log 1 push workout", description: "Log any push workout" },
    ],
    prerequisites: [],
    unlocks: ["diamond_push_up", "pike_push_up", "archer_push_up"],
    tips: ["Keep core tight", "Full range of motion"],
  },
  {
    id: "pull_up",
    name: "Pull-Up",
    icon: "🔼",
    tier: "beginner",
    domain: "pull",
    description: "Master the vertical pull.",
    requirements: [
      { type: "record_reps", target: "pull_ups", value: 1, label: "1 Pull-Up", description: "Set a pull-up record of at least 1 rep" },
    ],
    prerequisites: [],
    unlocks: ["explosive_pull_up", "archer_pull_up", "l_sit_pull_up"],
    tips: ["Dead hang first", "Scapular retraction"],
  },
  {
    id: "dead_hang",
    name: "Dead Hang",
    icon: "🧱",
    tier: "beginner",
    domain: "pull",
    description: "The foundation of grip and shoulder health.",
    requirements: [
      { type: "record_seconds", target: "dead_hang", value: 10, label: "10s Dead Hang", description: "Hold a dead hang for 10 seconds" },
    ],
    prerequisites: [],
    unlocks: ["dead_hang_30s", "scapular_pulls"],
    tips: ["Relax the shoulders", "Breathe steadily"],
  },
  {
    id: "squat",
    name: "Deep Squat",
    icon: "🏋️",
    tier: "beginner",
    domain: "legs",
    description: "Full depth squat with good form.",
    requirements: [
      { type: "workout_count", target: "squat", value: 3, label: "3 squat workouts", description: "Log 3 leg workouts" },
    ],
    prerequisites: [],
    unlocks: ["pistol_squat", "jump_squat"],
    tips: ["Heels flat", "Chest up"],
  },
  {
    id: "hollow_body",
    name: "Hollow Body Hold",
    icon: "🌊",
    tier: "beginner",
    domain: "core",
    description: "The foundation of all advanced skills.",
    requirements: [
      { type: "workout_count", target: "core", value: 2, label: "2 core workouts", description: "Log 2 core workouts" },
    ],
    prerequisites: [],
    unlocks: ["l_sit", "dragon_flag"],
    tips: ["Press lower back into floor", "Point toes"],
  },
];

// ─── INTERMEDIATE SKILLS ──────────────────────────────────────────────────────

const INTERMEDIATE_SKILLS: SkillDef[] = [
  {
    id: "muscle_up",
    name: "Muscle-Up",
    icon: "🔝",
    tier: "intermediate",
    domain: "pull",
    description: "The classic transition from pull to dip.",
    requirements: [
      { type: "record_reps",   target: "pull_ups", value: 12, label: "12 Pull-Ups",         description: "Set a pull-up record of 12+ reps" },
      { type: "mastery_level", target: "strength", value: 8,  label: "Strength Mastery 8",  description: "Reach Strength Mastery level 8" },
      { type: "level",         target: "level",    value: 5,  label: "Player Level 5",      description: "Reach player level 5" },
    ],
    prerequisites: ["pull_up"],
    unlocks: ["ring_muscle_up", "bar_muscle_up_clean"],
    journeyId: "muscle_up",
    featured: true,
    tips: ["Master the kip first", "Explosive pull required", "Transition is the key"],
  },
  {
    id: "l_sit",
    name: "L-Sit",
    icon: "📐",
    tier: "intermediate",
    domain: "core",
    description: "Compress your legs to parallel while supporting yourself.",
    requirements: [
      { type: "mastery_level", target: "strength",       value: 5, label: "Strength Mastery 5",       description: "Reach Strength Mastery level 5" },
      { type: "mastery_level", target: "static_strength", value: 3, label: "Static Strength Mastery 3", description: "Reach Static Strength level 3" },
      { type: "level",         target: "level",          value: 4, label: "Player Level 4",           description: "Reach player level 4" },
    ],
    prerequisites: ["hollow_body"],
    unlocks: ["v_sit", "l_sit_pull_up"],
    journeyId: "l_sit",
    tips: ["Tuck first", "Compression work daily"],
  },
  {
    id: "handstand",
    name: "Freestanding Handstand",
    icon: "🤸",
    tier: "intermediate",
    domain: "balance",
    description: "Hold a freestanding handstand for 5+ seconds.",
    requirements: [
      { type: "mastery_level",  target: "balance",   value: 6, label: "Balance Mastery 6",   description: "Reach Balance Mastery level 6" },
      { type: "level",          target: "level",     value: 6, label: "Player Level 6",      description: "Reach player level 6" },
      { type: "journey_stage",  target: "handstand", value: 3, label: "Handstand Journey Stage 3", description: "Complete 3 stages of the Handstand Journey" },
    ],
    prerequisites: [],
    unlocks: ["handstand_push_up", "handstand_walk", "one_arm_handstand"],
    journeyId: "handstand",
    featured: true,
    tips: ["Wall work daily", "Shoulder alignment critical"],
  },
  {
    id: "pistol_squat",
    name: "Pistol Squat",
    icon: "🦵",
    tier: "intermediate",
    domain: "legs",
    description: "Single-leg full depth squat.",
    requirements: [
      { type: "mastery_level", target: "strength", value: 6, label: "Strength Mastery 6", description: "Reach Strength Mastery level 6" },
      { type: "mastery_level", target: "mobility", value: 4, label: "Mobility Mastery 4", description: "Reach Mobility Mastery level 4" },
      { type: "level",         target: "level",    value: 5, label: "Player Level 5",     description: "Reach player level 5" },
    ],
    prerequisites: ["squat"],
    unlocks: ["shrimp_squat", "dragon_squat"],
    journeyId: "pistol_squat",
    tips: ["Heel elevated helps initially", "Hip mobility critical"],
  },
  {
    id: "archer_push_up",
    name: "Archer Push-Up",
    icon: "🏹",
    tier: "intermediate",
    domain: "push",
    description: "Unilateral pushing with extended arm.",
    requirements: [
      { type: "record_reps",   target: "push_ups", value: 20, label: "20 Push-Ups",        description: "Set a push-up record of 20+ reps" },
      { type: "mastery_level", target: "strength", value: 5,  label: "Strength Mastery 5", description: "Reach Strength Mastery level 5" },
    ],
    prerequisites: ["push_up"],
    unlocks: ["one_arm_push_up"],
    tips: ["Keep core tight", "Slow controlled movement"],
  },
  {
    id: "archer_pull_up",
    name: "Archer Pull-Up",
    icon: "🎋",
    tier: "intermediate",
    domain: "pull",
    description: "Unilateral pull-up with extended arm.",
    requirements: [
      { type: "record_reps",   target: "pull_ups", value: 15, label: "15 Pull-Ups",        description: "Set a pull-up record of 15+ reps" },
      { type: "mastery_level", target: "strength", value: 7,  label: "Strength Mastery 7", description: "Reach Strength Mastery level 7" },
    ],
    prerequisites: ["pull_up"],
    unlocks: ["one_arm_pull_up"],
    tips: ["Full retraction at top", "Control the negative"],
  },
  {
    id: "dead_hang_30s",
    name: "30s Dead Hang",
    icon: "⏱️",
    tier: "intermediate",
    domain: "pull",
    description: "Hold a dead hang for 30 seconds.",
    requirements: [
      { type: "record_seconds", target: "dead_hang", value: 30, label: "30s Dead Hang", description: "Hold a dead hang for 30 seconds" },
      { type: "mastery_level",  target: "grip",      value: 3,  label: "Grip Mastery 3", description: "Reach Grip Mastery level 3" },
    ],
    prerequisites: ["dead_hang"],
    unlocks: ["scapular_pulls"],
    tips: ["Use chalk if needed", "Relax the body"],
  },
];

// ─── ADVANCED SKILLS ─────────────────────────────────────────────────────────

const ADVANCED_SKILLS: SkillDef[] = [
  {
    id: "front_lever",
    name: "Front Lever",
    icon: "🎯",
    tier: "advanced",
    domain: "static",
    description: "Horizontal hold with arms overhead on the bar.",
    requirements: [
      { type: "record_reps",   target: "pull_ups",      value: 20, label: "20 Pull-Ups",              description: "Set a pull-up record of 20+" },
      { type: "mastery_level", target: "strength",      value: 15, label: "Strength Mastery 15",       description: "Reach Strength Mastery 15" },
      { type: "mastery_level", target: "static_strength", value: 12, label: "Static Strength Mastery 12", description: "Reach Static Strength Mastery 12" },
      { type: "journey_stage", target: "front_lever",   value: 5,  label: "Front Lever Journey Stage 5", description: "Complete 5 stages of the Front Lever Journey" },
      { type: "level",         target: "level",         value: 12, label: "Player Level 12",          description: "Reach player level 12" },
    ],
    prerequisites: ["pull_up", "l_sit", "dead_hang"],
    unlocks: ["straddle_front_lever", "full_front_lever"],
    journeyId: "front_lever",
    featured: true,
    tips: ["Tuck progression first", "Straight body line", "Depression and retraction"],
  },
  {
    id: "planche_lean",
    name: "Planche Lean",
    icon: "↗️",
    tier: "advanced",
    domain: "static",
    description: "Lean forward on straight arms with feet still grounded.",
    requirements: [
      { type: "record_reps",   target: "push_ups", value: 30, label: "30 Push-Ups",        description: "30+ push-up reps" },
      { type: "mastery_level", target: "strength", value: 10, label: "Strength Mastery 10", description: "Reach Strength Mastery 10" },
      { type: "level",         target: "level",    value: 8,  label: "Player Level 8",      description: "Reach player level 8" },
    ],
    prerequisites: ["push_up"],
    unlocks: ["tuck_planche"],
    journeyId: "planche",
    tips: ["Wrist preparation is crucial", "Forward lean angle matters"],
  },
  {
    id: "one_arm_push_up",
    name: "One Arm Push-Up",
    icon: "✊",
    tier: "advanced",
    domain: "push",
    description: "Full range push-up on a single arm.",
    requirements: [
      { type: "record_reps",   target: "push_ups", value: 40, label: "40 Push-Ups",         description: "40+ push-up reps" },
      { type: "mastery_level", target: "strength", value: 12, label: "Strength Mastery 12", description: "Reach Strength Mastery 12" },
      { type: "mastery_level", target: "balance",  value: 8,  label: "Balance Mastery 8",   description: "Reach Balance Mastery 8" },
      { type: "level",         target: "level",    value: 10, label: "Player Level 10",     description: "Reach player level 10" },
    ],
    prerequisites: ["archer_push_up"],
    unlocks: ["one_arm_push_up_diamond"],
    tips: ["Archer push-ups first", "Core alignment essential"],
  },
  {
    id: "handstand_push_up",
    name: "Handstand Push-Up",
    icon: "🔽",
    tier: "advanced",
    domain: "push",
    description: "Full range push-up in a handstand position.",
    requirements: [
      { type: "mastery_level", target: "strength", value: 12, label: "Strength Mastery 12", description: "Reach Strength Mastery 12" },
      { type: "mastery_level", target: "balance",  value: 10, label: "Balance Mastery 10",  description: "Reach Balance Mastery 10" },
      { type: "journey_stage", target: "handstand", value: 5, label: "Handstand Journey Stage 5", description: "Complete 5 stages of the Handstand Journey" },
      { type: "level",         target: "level",    value: 14, label: "Player Level 14",     description: "Reach player level 14" },
    ],
    prerequisites: ["handstand"],
    unlocks: ["free_hspu", "deficit_hspu"],
    tips: ["Wall-supported first", "Forehead to floor range"],
  },
  {
    id: "dragon_flag",
    name: "Dragon Flag",
    icon: "🐉",
    tier: "advanced",
    domain: "core",
    description: "Full body leverage exercise on a bench.",
    requirements: [
      { type: "mastery_level", target: "strength",       value: 10, label: "Strength Mastery 10",        description: "Reach Strength Mastery 10" },
      { type: "mastery_level", target: "static_strength", value: 8,  label: "Static Strength Mastery 8",  description: "Reach Static Strength Mastery 8" },
      { type: "level",         target: "level",          value: 10, label: "Player Level 10",            description: "Reach player level 10" },
    ],
    prerequisites: ["hollow_body", "l_sit"],
    unlocks: [],
    tips: ["Negative reps first", "Keep body rigid"],
  },
  {
    id: "v_sit",
    name: "V-Sit",
    icon: "✌️",
    tier: "advanced",
    domain: "core",
    description: "L-sit with legs elevated above parallel.",
    requirements: [
      { type: "record_seconds", target: "l_sit",         value: 10, label: "10s L-Sit",                  description: "Hold an L-sit for 10 seconds" },
      { type: "mastery_level",  target: "static_strength", value: 10, label: "Static Strength Mastery 10", description: "Reach Static Strength Mastery 10" },
      { type: "mastery_level",  target: "mobility",      value: 6,  label: "Mobility Mastery 6",          description: "Reach Mobility Mastery 6" },
      { type: "level",          target: "level",         value: 11, label: "Player Level 11",            description: "Reach player level 11" },
    ],
    prerequisites: ["l_sit"],
    unlocks: [],
    tips: ["Hip flexor strength is key", "Compression flexibility required"],
  },
];

// ─── ELITE SKILLS ─────────────────────────────────────────────────────────────

const ELITE_SKILLS: SkillDef[] = [
  {
    id: "human_flag",
    name: "Human Flag",
    icon: "🚩",
    tier: "elite",
    domain: "static",
    description: "Horizontal hold on a vertical pole.",
    requirements: [
      { type: "record_reps",   target: "pull_ups", value: 20, label: "20 Pull-Ups",         description: "20+ pull-up reps" },
      { type: "mastery_level", target: "strength", value: 20, label: "Strength Mastery 20", description: "Reach Strength Mastery 20" },
      { type: "mastery_level", target: "balance",  value: 18, label: "Balance Mastery 18",  description: "Reach Balance Mastery 18" },
      { type: "journey_stage", target: "human_flag", value: 4, label: "Human Flag Journey Stage 4", description: "Complete 4 stages of the Human Flag Journey" },
      { type: "level",         target: "level",    value: 20, label: "Player Level 20",     description: "Reach player level 20" },
    ],
    prerequisites: ["pull_up", "front_lever"],
    unlocks: [],
    journeyId: "human_flag",
    featured: true,
    tips: ["Lateral strength is unique", "Straddle position easier", "Shoulder press strength needed"],
  },
  {
    id: "tuck_planche",
    name: "Tuck Planche",
    icon: "🔄",
    tier: "elite",
    domain: "static",
    description: "Hold a planche with legs tucked to chest.",
    requirements: [
      { type: "record_reps",   target: "push_ups",      value: 50, label: "50 Push-Ups",              description: "50+ push-up reps" },
      { type: "mastery_level", target: "strength",      value: 18, label: "Strength Mastery 18",       description: "Reach Strength Mastery 18" },
      { type: "mastery_level", target: "static_strength", value: 15, label: "Static Strength Mastery 15", description: "Reach Static Strength Mastery 15" },
      { type: "mastery_level", target: "balance",       value: 12, label: "Balance Mastery 12",        description: "Reach Balance Mastery 12" },
      { type: "journey_stage", target: "planche",       value: 3,  label: "Planche Journey Stage 3",  description: "Complete 3 stages of the Planche Journey" },
      { type: "level",         target: "level",         value: 15, label: "Player Level 15",          description: "Reach player level 15" },
    ],
    prerequisites: ["planche_lean"],
    unlocks: ["advanced_tuck_planche", "straddle_planche"],
    journeyId: "planche",
    featured: true,
    tips: ["Shoulders must be fully depressed", "Wrist conditioning key"],
  },
  {
    id: "one_arm_pull_up",
    name: "One Arm Pull-Up",
    icon: "💎",
    tier: "elite",
    domain: "pull",
    description: "Pull-up performed on a single arm.",
    requirements: [
      { type: "record_reps",   target: "pull_ups", value: 25, label: "25 Pull-Ups",         description: "25+ pull-up reps" },
      { type: "mastery_level", target: "strength", value: 22, label: "Strength Mastery 22", description: "Reach Strength Mastery 22" },
      { type: "mastery_level", target: "grip",     value: 15, label: "Grip Mastery 15",     description: "Reach Grip Mastery 15" },
      { type: "journey_stage", target: "one_arm_pullup", value: 4, label: "One Arm Pull-Up Journey Stage 4", description: "Complete 4 stages" },
      { type: "level",         target: "level",    value: 22, label: "Player Level 22",     description: "Reach player level 22" },
    ],
    prerequisites: ["pull_up", "archer_pull_up"],
    unlocks: [],
    journeyId: "one_arm_pullup",
    featured: true,
    tips: ["Archer pull-ups bridge", "Wrist needs to be strong", "Gradual loading essential"],
  },
  {
    id: "pike_push_up",
    name: "Pike Push-Up",
    icon: "🏔️",
    tier: "intermediate",
    domain: "push",
    description: "Push-up in pike position targeting shoulders.",
    requirements: [
      { type: "record_reps",   target: "push_ups", value: 15, label: "15 Push-Ups",        description: "15+ push-up reps" },
      { type: "mastery_level", target: "strength", value: 4,  label: "Strength Mastery 4", description: "Reach Strength Mastery 4" },
    ],
    prerequisites: ["push_up"],
    unlocks: ["handstand_push_up"],
    tips: ["Hips high", "Head through at bottom"],
  },
];

// ─── LEGENDARY SKILLS ─────────────────────────────────────────────────────────

const LEGENDARY_SKILLS: SkillDef[] = [
  {
    id: "full_planche",
    name: "Full Planche",
    icon: "👐",
    tier: "legendary",
    domain: "static",
    description: "Hold a planche with body fully horizontal, legs together.",
    requirements: [
      { type: "mastery_level", target: "strength",       value: 30, label: "Strength Mastery 30",        description: "Reach Strength Mastery 30" },
      { type: "mastery_level", target: "static_strength", value: 25, label: "Static Strength Mastery 25", description: "Reach Static Strength Mastery 25" },
      { type: "mastery_level", target: "balance",        value: 20, label: "Balance Mastery 20",         description: "Reach Balance Mastery 20" },
      { type: "journey_stage", target: "planche",        value: 6,  label: "Planche Journey Complete",   description: "Complete the Planche Journey" },
      { type: "level",         target: "level",          value: 35, label: "Player Level 35",           description: "Reach player level 35" },
    ],
    prerequisites: ["tuck_planche"],
    unlocks: [],
    journeyId: "planche",
    featured: true,
    tips: ["Years of dedicated training", "Maximize wrist conditioning", "Straight arm strength"],
  },
  {
    id: "full_front_lever",
    name: "Full Front Lever",
    icon: "🌟",
    tier: "legendary",
    domain: "static",
    description: "Horizontal hold with body fully parallel to ground.",
    requirements: [
      { type: "record_reps",   target: "pull_ups",       value: 30, label: "30 Pull-Ups",               description: "30+ pull-up reps" },
      { type: "mastery_level", target: "strength",       value: 25, label: "Strength Mastery 25",        description: "Reach Strength Mastery 25" },
      { type: "mastery_level", target: "static_strength", value: 20, label: "Static Strength Mastery 20", description: "Reach Static Strength Mastery 20" },
      { type: "journey_stage", target: "front_lever",    value: 6,  label: "Front Lever Journey Stage 6", description: "Complete 6 stages" },
      { type: "level",         target: "level",          value: 20, label: "Player Level 20",           description: "Reach player level 20" },
    ],
    prerequisites: ["front_lever"],
    unlocks: [],
    journeyId: "front_lever",
    featured: true,
    tips: ["Straight body is the goal", "Back strength is paramount"],
  },
  {
    id: "iron_cross",
    name: "Iron Cross",
    icon: "✝️",
    tier: "legendary",
    domain: "static",
    description: "Hold body at 90° on rings with arms extended.",
    requirements: [
      { type: "mastery_level", target: "strength",       value: 35, label: "Strength Mastery 35",        description: "Reach Strength Mastery 35" },
      { type: "mastery_level", target: "static_strength", value: 30, label: "Static Strength Mastery 30", description: "Reach Static Strength Mastery 30" },
      { type: "level",         target: "level",          value: 40, label: "Player Level 40",           description: "Reach player level 40" },
      { type: "record_reps",   target: "pull_ups",       value: 25, label: "25 Pull-Ups",               description: "25+ pull-up reps" },
    ],
    prerequisites: ["one_arm_pull_up"],
    unlocks: [],
    featured: true,
    tips: ["Ring strength is unique", "Years of ring training required", "Straight arm conditioning from day 1"],
  },
];

export const ALL_SKILLS: SkillDef[] = [
  ...BEGINNER_SKILLS,
  ...INTERMEDIATE_SKILLS,
  ...ADVANCED_SKILLS,
  ...ELITE_SKILLS,
  ...LEGENDARY_SKILLS,
];

export const SKILL_MAP: Record<string, SkillDef> = Object.fromEntries(
  ALL_SKILLS.map((s) => [s.id, s])
);

export const FEATURED_SKILLS: SkillDef[] = ALL_SKILLS.filter((s) => s.featured);
