import { SkillNode } from "./skilltree-types";

// ─── PUSH TREE ────────────────────────────────────────────────────────────────

const PUSH_NODES: SkillNode[] = [
  {
    id: "push-up", name: "Push-Up", branch: "push", tier: 0, col: 2,
    description: "The foundational push movement. Master 30 clean reps with full range of motion — chest to floor, arms fully extended.",
    xpReward: 150, skillLevel: 1,
    requiredReps: 30, currentReps: 20, unit: "reps",
    status: "available", isEndgame: false,
    parents: [], unlockReqs: null,
  },
  {
    id: "diamond-push-up", name: "Diamond Push-Up", branch: "push", tier: 1, col: 0,
    description: "Hands form a diamond shape beneath the chest. Isolates triceps intensely. Crucial for pressing strength.",
    xpReward: 200, skillLevel: 2,
    requiredReps: 20, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "push-up", label: "Push-Up" }] },
  },
  {
    id: "wide-push-up", name: "Wide Push-Up", branch: "push", tier: 1, col: 1,
    description: "Hands placed wider than shoulder-width. Shifts load to chest. Builds the base for planche work.",
    xpReward: 175, skillLevel: 2,
    requiredReps: 25, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "push-up", label: "Push-Up" }] },
  },
  {
    id: "decline-push-up", name: "Decline Push-Up", branch: "push", tier: 1, col: 2,
    description: "Feet elevated on a surface, hands on floor. Targets upper chest and anterior deltoids. Gateway to handstand pressing.",
    xpReward: 175, skillLevel: 2,
    requiredReps: 20, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "push-up", label: "Push-Up" }] },
  },
  {
    id: "dips", name: "Dips", branch: "push", tier: 1, col: 3,
    description: "Parallel bar dips. The king of tricep exercises. Requires full depression at the top and deep dip at the bottom.",
    xpReward: 200, skillLevel: 2,
    requiredReps: 15, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "push-up", label: "Push-Up" }] },
  },
  {
    id: "archer-push-up", name: "Archer Push-Up", branch: "push", tier: 2, col: 0,
    description: "One arm bends while the other stays straight as a guide. The key regression toward one-arm push-up.",
    xpReward: 300, skillLevel: 3,
    requiredReps: 3, currentReps: 0, unit: "reps each side",
    status: "locked", isEndgame: false,
    parents: ["diamond-push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "diamond-push-up", label: "Diamond Push-Up" }] },
  },
  {
    id: "pike-push-up", name: "Pike Push-Up", branch: "push", tier: 2, col: 2,
    description: "Hips high in inverted V. Loads the shoulders vertically. The direct precursor to handstand push-ups.",
    xpReward: 250, skillLevel: 3,
    requiredReps: 15, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["decline-push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "decline-push-up", label: "Decline Push-Up" }] },
  },
  {
    id: "straight-bar-dips", name: "Straight Bar Dips", branch: "push", tier: 2, col: 3,
    description: "Dips on a straight bar, body leans forward. Develops bar muscle-up transition strength. Far harder than parallel bar dips.",
    xpReward: 300, skillLevel: 3,
    requiredReps: 8, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["dips"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "dips", label: "Dips" }] },
  },
  {
    id: "korean-dips", name: "Korean Dips", branch: "push", tier: 2, col: 4,
    description: "Bar behind the body, dipping backward. Extreme shoulder mobility and tricep strength. Rare and brutal.",
    xpReward: 350, skillLevel: 4,
    requiredReps: 3, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["dips"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "dips", label: "Dips" }] },
  },
  {
    id: "pseudo-planche-push-up", name: "Pseudo Planche Push-Up", branch: "push", tier: 3, col: 1,
    description: "Hands rotated outward, lean forward past hands before pushing. Builds wrist, shoulder, and planche-specific strength.",
    xpReward: 400, skillLevel: 4,
    requiredReps: 8, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["push-up", "pike-push-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "push-up", label: "Push-Up" }, { nodeId: "pike-push-up", label: "Pike Push-Up" }] },
  },
  {
    id: "handstand-push-up", name: "Handstand Push-Up", branch: "push", tier: 4, col: 2,
    description: "Full overhead press inverted against a wall. One of the most impressive pressing feats in bodyweight training.",
    xpReward: 500, skillLevel: 4,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["pike-push-up", "handstand-hold"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "pike-push-up", label: "Pike Push-Up" }, { nodeId: "handstand-hold", label: "Handstand Hold" }] },
  },
  {
    id: "one-arm-push-up", name: "One-Arm Push-Up", branch: "push", tier: 5, col: 1,
    description: "The pinnacle of push strength. Full ROM with one arm, feet hip-width. Requires mastery of the entire push tree.",
    xpReward: 1000, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: true,
    parents: ["archer-push-up", "handstand-push-up"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "archer-push-up", label: "Archer Push-Up" }, { nodeId: "handstand-push-up", label: "Handstand Push-Up" }],
      branches: [{ branch: "push", label: "100% Push Tree" }],
    },
  },
  {
    id: "full-planche", name: "Full Planche", branch: "push", tier: 5, col: 3,
    description: "Body horizontal, arms locked, feet off the ground. The ultimate static pushing skill requiring total mastery across all trees.",
    xpReward: 1200, skillLevel: 5,
    requiredReps: 3, currentReps: 0, unit: "second hold",
    status: "locked", isEndgame: true,
    parents: ["pseudo-planche-push-up", "l-sit", "handstand"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "pseudo-planche-push-up", label: "Pseudo Planche Push-Up" }, { nodeId: "l-sit", label: "L-Sit" }, { nodeId: "straddle-planche", label: "Straddle Planche" }],
      branches: [{ branch: "push", label: "100% Push Tree" }, { branch: "core", label: "100% Core Tree" }, { branch: "skill", label: "100% Skill & Balance Tree" }],
    },
  },
  {
    id: "planche-push-up", name: "Planche Push-Up", branch: "push", tier: 6, col: 3,
    description: "A push-up from full planche to planche. The hardest push movement in existence. Reserved for legends only.",
    xpReward: 1500, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: true,
    parents: ["full-planche"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "full-planche", label: "Full Planche" }],
      branches: [{ branch: "push", label: "100% Push Tree" }, { branch: "skill", label: "100% Skill & Balance Tree" }],
    },
  },
];

// ─── PULL TREE ────────────────────────────────────────────────────────────────

const PULL_NODES: SkillNode[] = [
  {
    id: "dead-hang", name: "Dead Hang", branch: "pull", tier: 0, col: 2,
    description: "Full bodyweight hang from a bar, arms straight. Builds grip, shoulder health, and decompresses the spine. The gateway to all pulling.",
    xpReward: 100, skillLevel: 1,
    requiredReps: 90, currentReps: 60, unit: "seconds",
    status: "available", isEndgame: false,
    parents: [], unlockReqs: null,
  },
  {
    id: "chin-up", name: "Chin-Up", branch: "pull", tier: 1, col: 1,
    description: "Supinated (palms facing you) grip pull-up. Maximally activates biceps. Typically easier than pronated pull-ups.",
    xpReward: 175, skillLevel: 2,
    requiredReps: 15, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["dead-hang"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "dead-hang", label: "Dead Hang" }] },
  },
  {
    id: "pull-up", name: "Pull-Up", branch: "pull", tier: 1, col: 3,
    description: "Pronated (palms away) grip. The standard pull-up. Requires more lat activation than chin-up. Foundation of all advanced pulling.",
    xpReward: 200, skillLevel: 2,
    requiredReps: 15, currentReps: 10, unit: "reps",
    status: "available", isEndgame: false,
    parents: ["dead-hang"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "dead-hang", label: "Dead Hang" }] },
  },
  {
    id: "wide-pull-up", name: "Wide Pull-Up", branch: "pull", tier: 2, col: 1,
    description: "Grip wider than shoulder-width. Heavy lat isolation. Required for the wide back development needed in advanced skills.",
    xpReward: 225, skillLevel: 2,
    requiredReps: 12, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "pull-up", label: "Pull-Up" }] },
  },
  {
    id: "close-grip-pull-up", name: "Close-Grip Pull-Up", branch: "pull", tier: 2, col: 2,
    description: "Hands close together, neutral or pronated grip. High bicep and inner lat activation. Builds the pulling strength for one-arm work.",
    xpReward: 225, skillLevel: 2,
    requiredReps: 15, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "pull-up", label: "Pull-Up" }] },
  },
  {
    id: "commando-pull-up", name: "Commando Pull-Up", branch: "pull", tier: 2, col: 3,
    description: "Parallel grip on a single bar, alternating which side you pull to. Builds unilateral pulling awareness.",
    xpReward: 250, skillLevel: 3,
    requiredReps: 8, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "pull-up", label: "Pull-Up" }] },
  },
  {
    id: "archer-pull-up", name: "Archer Pull-Up", branch: "pull", tier: 3, col: 1,
    description: "One arm pulls while the other assists with an extended arm. The most direct regression toward one-arm pull-up.",
    xpReward: 400, skillLevel: 4,
    requiredReps: 3, currentReps: 0, unit: "reps each side",
    status: "locked", isEndgame: false,
    parents: ["wide-pull-up", "close-grip-pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "wide-pull-up", label: "Wide Pull-Up" }, { nodeId: "close-grip-pull-up", label: "Close-Grip Pull-Up" }] },
  },
  {
    id: "typewriter-pull-up", name: "Typewriter Pull-Up", branch: "pull", tier: 4, col: 1,
    description: "Pull up to the bar then traverse side-to-side at the top. Builds massive unilateral strength and coordination.",
    xpReward: 450, skillLevel: 4,
    requiredReps: 3, currentReps: 0, unit: "reps each side",
    status: "locked", isEndgame: false,
    parents: ["archer-pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "archer-pull-up", label: "Archer Pull-Up" }] },
  },
  {
    id: "high-pull-up", name: "High Pull-Up", branch: "pull", tier: 5, col: 1,
    description: "Pull explosively until the chest or hips reach the bar. The power expression needed for muscle-up transitions.",
    xpReward: 500, skillLevel: 4,
    requiredReps: 5, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["typewriter-pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "typewriter-pull-up", label: "Typewriter Pull-Up" }] },
  },
  {
    id: "muscle-up", name: "Muscle-Up", branch: "pull", tier: 6, col: 2,
    description: "Explosive pull transitioning above the bar into a dip. The iconic bar skill. Power and technique combined.",
    xpReward: 600, skillLevel: 4,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["high-pull-up", "straight-bar-dips"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "high-pull-up", label: "High Pull-Up" }, { nodeId: "straight-bar-dips", label: "Straight Bar Dips" }] },
  },
  {
    id: "strict-muscle-up", name: "Strict Muscle-Up", branch: "pull", tier: 7, col: 2,
    description: "Muscle-up performed with zero kip or swing. Pure pressing and pulling strength. Massively harder than kipping version.",
    xpReward: 750, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["muscle-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "muscle-up", label: "Muscle-Up" }] },
  },
  {
    id: "one-arm-pull-up", name: "One-Arm Pull-Up", branch: "pull", tier: 7, col: 0,
    description: "The absolute pinnacle of pulling strength. Full ROM pull-up using a single arm. World-class bodyweight strength.",
    xpReward: 1200, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: true,
    parents: ["archer-pull-up", "typewriter-pull-up", "high-pull-up"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "archer-pull-up", label: "Archer Pull-Up" }, { nodeId: "typewriter-pull-up", label: "Typewriter Pull-Up" }, { nodeId: "high-pull-up", label: "High Pull-Up" }],
      branches: [{ branch: "pull", label: "100% Pull Tree" }],
    },
  },
  {
    id: "front-lever-pull-up", name: "Front Lever Pull-Up", branch: "pull", tier: 8, col: 2,
    description: "A pull-up performed from and returning to the front lever position. One of the most elite pulling feats imaginable.",
    xpReward: 1400, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: true,
    parents: ["front-lever", "strict-muscle-up"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "front-lever", label: "Front Lever" }],
      branches: [{ branch: "pull", label: "100% Pull Tree" }],
    },
  },
  {
    id: "hefesto", name: "Hefesto", branch: "pull", tier: 9, col: 2,
    description: "Front lever pull to inverted hang to back lever in one fluid motion. Named after the Greek god of fire. Extreme elite skill.",
    xpReward: 2000, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: true,
    parents: ["front-lever-pull-up", "strict-muscle-up"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "front-lever-pull-up", label: "Front Lever Pull-Up" }, { nodeId: "strict-muscle-up", label: "Strict Muscle-Up" }],
      branches: [{ branch: "pull", label: "100% Pull Tree" }],
    },
  },
];

// ─── CORE TREE ────────────────────────────────────────────────────────────────

const CORE_NODES: SkillNode[] = [
  {
    id: "plank", name: "Plank", branch: "core", tier: 0, col: 2,
    description: "The foundational isometric core hold. Neutral spine, elbows under shoulders, full-body tension. Gateway to all core work.",
    xpReward: 100, skillLevel: 1,
    requiredReps: 120, currentReps: 90, unit: "seconds",
    status: "available", isEndgame: false,
    parents: [], unlockReqs: null,
  },
  {
    id: "hollow-hold", name: "Hollow Hold", branch: "core", tier: 1, col: 1,
    description: "Lower back pressed to floor, legs and arms extended, body curved like a banana. The fundamental gymnastics core position.",
    xpReward: 175, skillLevel: 2,
    requiredReps: 60, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["plank"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "plank", label: "Plank" }] },
  },
  {
    id: "side-plank", name: "Side Plank", branch: "core", tier: 1, col: 3,
    description: "Lateral isometric hold on one forearm or hand. Oblique and hip abductor strength. Prerequisite for human flag.",
    xpReward: 175, skillLevel: 2,
    requiredReps: 60, currentReps: 0, unit: "seconds each side",
    status: "locked", isEndgame: false,
    parents: ["plank"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "plank", label: "Plank" }] },
  },
  {
    id: "hanging-knee-raise", name: "Hanging Knee Raise", branch: "core", tier: 2, col: 0,
    description: "Hanging from a bar, raise knees to chest under control. Builds hip flexor strength and teaches hanging core engagement.",
    xpReward: 150, skillLevel: 2,
    requiredReps: 20, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["hollow-hold"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "hollow-hold", label: "Hollow Hold" }] },
  },
  {
    id: "hanging-leg-raise", name: "Hanging Leg Raise", branch: "core", tier: 2, col: 1,
    description: "Straight-leg raise to horizontal or above while hanging. Requires posterior pelvic tilt and full hip flexor strength.",
    xpReward: 250, skillLevel: 3,
    requiredReps: 15, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["hollow-hold"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "hollow-hold", label: "Hollow Hold" }] },
  },
  {
    id: "toes-to-bar", name: "Toes-To-Bar", branch: "core", tier: 3, col: 0,
    description: "Feet touch the bar while hanging. Requires full hip flexion, lat engagement, and swing control. A true core power move.",
    xpReward: 300, skillLevel: 3,
    requiredReps: 8, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["hanging-leg-raise"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "hanging-leg-raise", label: "Hanging Leg Raise" }] },
  },
  {
    id: "windshield-wipers", name: "Windshield Wipers", branch: "core", tier: 3, col: 1,
    description: "Hanging with legs raised horizontal, sweep side to side like wipers. Rotational core strength and oblique power.",
    xpReward: 300, skillLevel: 3,
    requiredReps: 10, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["hanging-leg-raise"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "hanging-leg-raise", label: "Hanging Leg Raise" }] },
  },
  {
    id: "l-sit", name: "L-Sit", branch: "core", tier: 3, col: 2,
    description: "On parallettes or dip bars, legs extended parallel to floor. Requires hip flexor strength, tricep pushing, and core compression.",
    xpReward: 400, skillLevel: 3,
    requiredReps: 15, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["hanging-leg-raise", "hollow-hold"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "hanging-leg-raise", label: "Hanging Leg Raise" }, { nodeId: "hollow-hold", label: "Hollow Hold" }] },
  },
  {
    id: "v-sit", name: "V-Sit", branch: "core", tier: 4, col: 2,
    description: "L-sit with legs raised above horizontal in a V shape. Far greater compression strength required. Gymnastic level core control.",
    xpReward: 500, skillLevel: 4,
    requiredReps: 10, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["l-sit"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "l-sit", label: "L-Sit" }] },
  },
  {
    id: "dragon-flag", name: "Dragon Flag", branch: "core", tier: 4, col: 1,
    description: "Popularized by Bruce Lee. Body held rigid from shoulders, lowering and raising with total-body tension. Ultimate core strength.",
    xpReward: 550, skillLevel: 4,
    requiredReps: 5, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["l-sit", "hanging-leg-raise"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "l-sit", label: "L-Sit" }, { nodeId: "hanging-leg-raise", label: "Hanging Leg Raise" }] },
  },
  {
    id: "front-lever", name: "Front Lever", branch: "core", tier: 5, col: 1,
    description: "Body horizontal face-up, arms straight overhead gripping a bar. Demands total lat, core, and posterior chain strength.",
    xpReward: 700, skillLevel: 5,
    requiredReps: 5, currentReps: 0, unit: "second hold",
    status: "locked", isEndgame: false,
    parents: ["dragon-flag", "pull-up"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "dragon-flag", label: "Dragon Flag" }, { nodeId: "pull-up", label: "Pull-Up" }] },
  },
  {
    id: "human-flag", name: "Human Flag", branch: "core", tier: 6, col: 2,
    description: "Body horizontal sideways on a vertical pole. The most visually stunning static skill. Demands total lateral body strength.",
    xpReward: 900, skillLevel: 5,
    requiredReps: 5, currentReps: 0, unit: "second hold",
    status: "locked", isEndgame: false,
    parents: ["side-plank", "front-lever"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "side-plank", label: "Side Plank" }, { nodeId: "front-lever", label: "Front Lever" }] },
  },
];

// ─── SKILL & BALANCE TREE ─────────────────────────────────────────────────────

const SKILL_NODES: SkillNode[] = [
  {
    id: "frog-stand", name: "Frog Stand", branch: "skill", tier: 0, col: 2,
    description: "Knees resting on upper arms, balanced on hands. The first taste of inverted balance. Most people can learn this in a session.",
    xpReward: 100, skillLevel: 1,
    requiredReps: 20, currentReps: 0, unit: "seconds",
    status: "available", isEndgame: false,
    parents: [], unlockReqs: null,
  },
  {
    id: "crow-pose", name: "Crow Pose", branch: "skill", tier: 1, col: 2,
    description: "Arms more extended than frog stand, knees higher on triceps. Requires more wrist strength and balance. Yoga-calisthenics crossover skill.",
    xpReward: 175, skillLevel: 2,
    requiredReps: 20, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["frog-stand"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "frog-stand", label: "Frog Stand" }] },
  },
  {
    id: "elbow-lever", name: "Elbow Lever", branch: "skill", tier: 2, col: 2,
    description: "Body balanced horizontally on one elbow pressed into hip. A gymnastics floor skill requiring unusual strength and balance.",
    xpReward: 300, skillLevel: 3,
    requiredReps: 10, currentReps: 5, unit: "seconds",
    status: "available", isEndgame: false,
    parents: ["crow-pose"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "crow-pose", label: "Crow Pose" }] },
  },
  {
    id: "wall-walk", name: "Wall Walk", branch: "skill", tier: 3, col: 2,
    description: "Walk hands toward wall from push-up to full handstand against the wall. Builds shoulder stability and handstand comfort.",
    xpReward: 200, skillLevel: 2,
    requiredReps: 5, currentReps: 0, unit: "reps",
    status: "locked", isEndgame: false,
    parents: ["elbow-lever"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "elbow-lever", label: "Elbow Lever" }] },
  },
  {
    id: "handstand-hold", name: "Handstand Hold", branch: "skill", tier: 4, col: 2,
    description: "Wall-supported handstand for 30 seconds. Builds the foundational shoulder endurance and inversion comfort needed for freestanding work.",
    xpReward: 300, skillLevel: 3,
    requiredReps: 30, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["wall-walk"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "wall-walk", label: "Wall Walk" }] },
  },
  {
    id: "handstand", name: "Handstand", branch: "skill", tier: 5, col: 1,
    description: "Freestanding handstand for 10 seconds. The cornerstone skill of gymnastics. Requires total upper body control and balance mastery.",
    xpReward: 500, skillLevel: 4,
    requiredReps: 10, currentReps: 0, unit: "second hold",
    status: "locked", isEndgame: false,
    parents: ["handstand-hold"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "handstand-hold", label: "Handstand Hold" }] },
  },
  {
    id: "back-lever", name: "Back Lever", branch: "skill", tier: 5, col: 3,
    description: "Body horizontal face-down, arms overhead gripping a bar or rings. Intense bicep tendon and shoulder flexibility demand.",
    xpReward: 600, skillLevel: 4,
    requiredReps: 5, currentReps: 0, unit: "second hold",
    status: "locked", isEndgame: false,
    parents: ["handstand-hold"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "handstand-hold", label: "Handstand Hold" }] },
  },
  {
    id: "handstand-walk", name: "Handstand Walk", branch: "skill", tier: 6, col: 1,
    description: "Walking on your hands for 10 steps. Dynamic balance and shoulder control. A crowd-stopping display of skill.",
    xpReward: 600, skillLevel: 4,
    requiredReps: 10, currentReps: 0, unit: "steps",
    status: "locked", isEndgame: false,
    parents: ["handstand"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "handstand", label: "Handstand" }] },
  },
  {
    id: "tuck-planche", name: "Tuck Planche", branch: "skill", tier: 6, col: 2,
    description: "Planche with knees tucked to chest. The first real planche progression. Requires serious wrist, shoulder, and pushing strength.",
    xpReward: 650, skillLevel: 4,
    requiredReps: 5, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["handstand-hold", "l-sit"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "handstand-hold", label: "Handstand Hold" }, { nodeId: "l-sit", label: "L-Sit" }] },
  },
  {
    id: "straddle-planche", name: "Straddle Planche", branch: "skill", tier: 7, col: 2,
    description: "Planche with legs straddled wide. Reduces rotational demand slightly compared to full planche. Still requires elite upper body strength.",
    xpReward: 800, skillLevel: 5,
    requiredReps: 5, currentReps: 0, unit: "seconds",
    status: "locked", isEndgame: false,
    parents: ["tuck-planche"],
    unlockReqs: { type: "nodes", nodes: [{ nodeId: "tuck-planche", label: "Tuck Planche" }] },
  },
  {
    id: "one-arm-handstand", name: "One-Arm Handstand", branch: "skill", tier: 8, col: 2,
    description: "Freestanding handstand on a single arm. One of the rarest and most impressive feats in all of calisthenics. True endgame.",
    xpReward: 2000, skillLevel: 5,
    requiredReps: 1, currentReps: 0, unit: "successful hold",
    status: "locked", isEndgame: true,
    parents: ["handstand", "full-planche"],
    unlockReqs: {
      type: "both",
      nodes: [{ nodeId: "full-planche", label: "Full Planche" }],
      branches: [{ branch: "skill", label: "100% Skill & Balance Tree" }],
    },
  },
];

// ─── Foundation Node ──────────────────────────────────────────────────────────

// Foundation Training is the single starting node (cross-branch gateway)
// It's represented virtually — when completed, the 4 root nodes unlock
// We handle this in logic, not as a node in any branch.

// ─── Exports ──────────────────────────────────────────────────────────────────

export const ALL_NODES: SkillNode[] = [
  ...PUSH_NODES,
  ...PULL_NODES,
  ...CORE_NODES,
  ...SKILL_NODES,
];

export const NODE_MAP: Record<string, SkillNode> = Object.fromEntries(
  ALL_NODES.map((n) => [n.id, n])
);

export const BRANCH_NODES: Record<string, SkillNode[]> = {
  push:  PUSH_NODES,
  pull:  PULL_NODES,
  core:  CORE_NODES,
  skill: SKILL_NODES,
};

// Root nodes per branch (unlocked after Foundation Training)
export const BRANCH_ROOTS: Record<string, string> = {
  push:  "push-up",
  pull:  "dead-hang",
  core:  "plank",
  skill: "frog-stand",
};
